### ISSUE TITLE
Threads Stop working

### ISSUE THREAD

**Issue by camay015** [yasserg/crawler4j#1]
The crawler works with the  web pages using in BasicCrawlcontroller 
 //  controller.addSeed("http://www.ics.uci.edu/~yganjisa/");
             // controller.addSeed("http://www.ics.uci.edu/~lopes/");
             // controller.addSeed("http://www.ics.uci.edu/");

but NO other web pages appear to work.  One example is below

Docid: 1
URL: http://www.unisa.edu.au/
Docid of parent page: 0
Text length: 2007
Html length: 14538
# Number of outgoing links: 90

10017 [Thread-1] INFO crawler.CrawlController  - It looks like no thread is working, waiting for 10 seconds to make sure...
20023 [Thread-1] INFO crawler.CrawlController  - No thread is working and no more URLs are in queue waiting for another 10 seconds to make sure...
30024 [Thread-1] INFO crawler.CrawlController  - All of the crawlers are stopped. Finishing the process...
30025 [Thread-1] INFO crawler.CrawlController  - Waiting for 10 seconds before final clean up...

**Comment by oliverln** [comment]
do you slove it ? how to slove it?

**Comment by oliverln** [comment]
well,my problem  is ，when i use crawler4j is ok ,but when i use crawler4j with quartz ,the peoblem is: 
1:48:05.753 [DefaultQuartzScheduler_Worker-1] INFO edu.uci.ics.crawler4j.crawler.CrawlController - Crawler 1 started
11:48:05.753 [DefaultQuartzScheduler_Worker-1] INFO edu.uci.ics.crawler4j.crawler.CrawlController - Crawler 2 started
Aggregated Statistics:
	Processed Pages: {}0
	Total Links found: {}0
	Total Text Size: {}0
11:48:05.757 [DefaultQuartzScheduler_Worker-2] INFO edu.uci.ics.crawler4j.crawler.CrawlController - Crawler 1 started
11:48:05.757 [DefaultQuartzScheduler_Worker-2] INFO edu.uci.ics.crawler4j.crawler.CrawlController - Crawler 2 started
Aggregated Statistics:
	Processed Pages: {}0
	Total Links found: {}0
	Total Text Size: {}0
11:48:15.755 [Thread-1] INFO edu.uci.ics.crawler4j.crawler.CrawlController - It looks like no thread is working, waiting for 10 seconds to make sure...
11:48:15.758 [Thread-2] INFO edu.uci.ics.crawler4j.crawler.CrawlController - It looks like no thread is working, waiting for 10 seconds to make sure...
11:48:25.755 [Thread-1] INFO edu.uci.ics.crawler4j.crawler.CrawlController - No thread is working and no more URLs are in queue waiting for another 10 seconds to make sure...
11:48:25.758 [Thread-2] INFO edu.uci.ics.crawler4j.crawler.CrawlController - No thread is working and no more URLs are in queue waiting for another 10 seconds to make sure...
11:48:27.821 [DefaultQuartzScheduler_QuartzSchedulerThread] DEBUG org.quartz.core.QuartzSchedulerThread - batch acquisition of 0 triggers
11:48:35.756 [Thread-1] INFO edu.uci.ics.crawler4j.crawler.CrawlController - All of the crawlers are stopped. Finishing the process...
11:48:35.756 [Thread-1] INFO edu.uci.ics.crawler4j.crawler.WebCrawler - Crawler 1 > Processed Pages: 0
11:48:35.757 [Thread-1] INFO edu.uci.ics.crawler4j.crawler.WebCrawler - Crawler 1 > Total Links Found: 0
11:48:35.757 [Thread-1] INFO edu.uci.ics.crawler4j.crawler.WebCrawler - Crawler 1 > Total Text Size: 0
