### ISSUE TITLE
[Request] Release new version

### ISSUE THREAD

**Issue by rpiaggio** [yasserg/crawler4j#100]
A significant number of issues have been addressed since the 4.1 release in February.

We would like to stick to the official dependency and therefore kindly request that a new version be released.

Thank you!

**Comment by cameroncan** [comment]
+1

**Comment by s17t** [comment]
+1

**Comment by thanhpd** [comment]
+1

**Comment by yasserg** [comment]
Done. It should show up in central repo soon.
