### ISSUE TITLE
Spring & data provider

### ISSUE THREAD

**Issue by prigozhinroman** [yasserg/crawler4j#101]
Are there any plans to spring enable this project ?
Also, how do you guys deal with extending this crawler to persist data into let say mongodb ? I had to actually fork this project to pass data provider through a configuration so I can persist data right after parsing it. But the main issue remains that I can't instantiate crawler on demand based on database configurations let say so I can create a farm of crawlers instantiated on demand.

**Comment by s17t** [comment]
Hi! Since 4.1 version you can inject in the CrawController a WebCrawlerFactory implementation so you can you use Spring DI mechanims.

The persistence layer should be not concern of the crawling library, imho.

**Comment by prigozhinroman** [comment]
Hi Yasser,
  Thank you for your answer, I completely agree that persistence should not be a concern of the crawler.
  I was using version 4.1.5 which didn’t have factory functionality so I couldn’t pass persistence implementation with spring and I had to rewrite some of the source code to do that. I see that in version 4.2 there is a way to pass a factory, thank you.
