### ISSUE TITLE
Follow 302er redirects

### ISSUE THREAD

**Issue by temkretz** [yasserg/crawler4j#104]
Hello,

I try to crawl a site which has a bunch of links which result in a 302er redirect. How can I tell crawler4j to follow these redirects? I know I can show the status code by overriding "handlePageStatusCode()" but I don't know how to follow the header..

**Comment by Chaiavi** [comment]
https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java#L399

CrawlConfig.setFollowRedirects(true);

**Comment by temkretz** [comment]
I already tried this as followRedirects defaults to true, doesn't work :/

**Comment by Chaiavi** [comment]
Sounds wierd

try debugging it to see the whole picture


It should work...

**Comment by temkretz** [comment]
What I do is, I log the current URL wihthin the "shouldVisit()" and the "visit()"-method. This way I can see the URLs which have successfully been found and been fetched.

I also set "config.setFollowRedirects(true);".

I see all the correct URLs when logging from "shouldVisit()".
I only see the URLs with http-status 400 when logging from the "visit()"-method.

Does it have something to do with the crawling depth? Does following links increases the depth?

**Comment by Chaiavi** [comment]
That is very weird

1. Follow redirects isn't connected to the depth AFAIK
2. Why do you get the 4xx status pages at all ?  these are not found pages.


Maybe this is a bug?



Can you debug the webCrawler, around here:
https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java#L331

**Comment by temkretz** [comment]
my bad, I see all URLs with status-code 200 ;)

Could it be, that "followed-urls" re-call shouldVisit() ?
So maybe my shouldVisit() method filters them out?

**Comment by temkretz** [comment]
Okay I got it! I just needed to analyse the referringsPage-WebURL because a redirect triggers the "shouldVisit()" again, didn't know that.

Anyway, thanks for your help! ;)
