### ISSUE TITLE
support for script src tag

### ISSUE THREAD

**Issue by code-911** [yasserg/crawler4j#113]
Hello!

Thank you for good code! I really liked it.

Request: I add a tag can not be supported

<script src = "/link.js"> 

in the class

edu.uci.ics.crawler4j.parser.HtmlContentHandler

Links from such elements are not parsed and not processed and they are very necessary.

Thank you in advance.

**Comment by jbfbell** [comment]
I saw the commit from a few days ago that said it should support script tags, is that not ready yet? Ive tried running the current version of master and it does not seem to pick up script tag src links.

**Comment by s17t** [comment]
@jbfbell that patch works, [here](https://github.com/yasserg/crawler4j/commit/be41378ba07e8264bf7aef6ed280d70f89bef63e) a more large test. If you can show use the code you are using.

**Comment by jbfbell** [comment]
What would be helpful for me to show?  I put a breakpoint in "shouldVisit" when I filter the parseData outgoingUrls for anything which contains "js" I find zero results.

**Comment by s17t** [comment]
@jbfbell could you provide the HTML source page you are crawling ? If it is public please paste the link.

**Comment by jbfbell** [comment]
the seed url is [bluenile.com](http://www.bluenile.com)

**Comment by jbfbell** [comment]
Sorry @s17t It was a caching issue with my local machine, I was not getting the latest version like I was expecting.  This issue is resolved.

**Comment by s17t** [comment]
Thank you! Good to known.
