### ISSUE TITLE
can't crawl the js file 

### ISSUE THREAD

**Issue by YZCSZHIWJ** [yasserg/crawler4j#116]
why I can't crawl the js file! need some config? if someone know please tell me

**Comment by rzo1** [comment]
Please provide more detailed information, e.g. source code or related Web-page.

Make sure, that the file extension ".js" is not excluded via 

    private final static Pattern FILTERS = Pattern.compile(".*(\\.(css|js|gif|jpg"
                                                           + "|png|mp3|mp3|zip|gz))$");

in your 

  public boolean shouldVisit(Page referringPage, WebURL url)

method implementation.

**Comment by mohdalihpk** [comment]
rzo1, It even don't try to fetch the js. I have tried your solution.

**Comment by rzo1** [comment]
Can you post your custom `crawler` implementation?

**Comment by bgoldowsky** [comment]
I believe the issue here is the same as #113 -- <script> is not included in the list of tags scanned for outgoing links in edu.uci.ics.crawler4j.parser.HtmlContentHandler .  It would be good to add.
