### ISSUE TITLE
Allow crawling of websites requiring authentication

### ISSUE THREAD

**Issue by nicosensei** [yasserg/crawler4j#12]
Either to personal or institutional (archiving) use, some content on websites needs that the user has authenticated before accessing it.

We should implement URL-pattern or domain based authentication and be able to check for session validity and enrich the HTTP requests that the crawler issues with authentication-related data (headers, cookies, etc...)

**Comment by s17t** [comment]
There is support for basic auth and form auth (cookie-based). If you implementations of more authentication please open an issue.
