### ISSUE TITLE
Add method to visit a page but not add its children

### ISSUE THREAD

**Issue by bgoldowsky** [yasserg/crawler4j#129]
Right now any page that returns true for shouldVisit() also has all its outgoing links added to the queue by WebCrawler.processPage().  I would like to have a way to specify, for some pages, that outgoing links should be ignored.  

One use case would be implementing a crawler that respects the meta tag `<meta name="robots" content="index, nofollow">`

My use case: I want to check the links on my site, including both internal links and external links.  But once I've loaded the page an external link points to, I don't want to go any further (or else I would end up checking the entire internet).  Yes, this is possible to implement by looking at referring pages in my shouldVisit() method, but it feels wasteful to add all those outgoing links to the queue only to drop them later.

**Comment by Chaiavi** [comment]
What about these configurations?

 /*
     * You can set the maximum crawl depth here. The default value is -1 for
     * unlimited depth
     */
    config.setMaxDepthOfCrawling(2);

    /*
     * You can set the maximum number of pages to crawl. The default value
     * is -1 for unlimited number of pages
     */
    config.setMaxPagesToFetch(1000);




You can use each one to solve your problem.
You can set it to crawl only 1 page
OR
You can set the depth to 0 or 1

**Comment by bgoldowsky** [comment]
I do want to crawl my whole site, which has several hundred pages and a non-zero depth, so these configurations won't help me.

For clarity, here is my current workaround (in the `shouldVisit(referringPage, url)` method).   baseUrl is set to something like http://my-site.example.com/ :

`    String href = url.getURL()`
`    String referrer = referringPage.getWebURL().getURL();`
`    boolean shouldVisit = href.startsWith(baseUrl)
        || referrer.startsWith(baseUrl)
        || referringPage.isRedirect();`

This works, but only by adding hundreds of potential links to the queue and then discarding them later.

**Comment by Chaiavi** [comment]
The way you do it is the best way of doing it.

Don't think about performance here as in the scenario you show it is really
minor as the page is already parsed anyway so no additional CPU is added.
No networking is used also for this code (of adding hundreds or thousands
of links then discarding them).


The only additional resource is some memory (hundreds/thousands of links)
which will take less than a single megabyte of memory for 2'000 links - and
even that will be only temporary as they will get discarded.
And CPU is really minor as searching withing the internal DB for those
links and discarding them is really a very small thing (too hard for me to
estimate as I it depends on the size of the DB etc) - we are talking
several seconds max for each thousand links

**Comment by bgoldowsky** [comment]
My workaround code turns out to be not just confusing but logically wrong - it checks links from external sites back into the main site, which was not desired.  I ended up implementing the requested feature myself in a fork and will submit a pull request -- it's much cleaner than the workaround and harmless for anyone who doesn't need it.
