### ISSUE TITLE
Cant make it work with Postgresql

### ISSUE THREAD

**Issue by justusual** [yasserg/crawler4j#133]
I've been trying to make it to store the data in PostgreSQL but I cant, I need help

**Comment by rzo1** [comment]
So what have you tried so far?

**Comment by justusual** [comment]
I made the crawler4j work, connected to the database. Successfully inserted data into the table. But I am having trouble making it to automatically store the data from the websites to the database, I tried `         stmt = c.createStatement();
   String sql = "INSERT INTO sobereno (datumvreme, websajt, zbor) "
         + "VALUES ('09 May 201', 'links', 'text');";
         stmt.executeUpdate(sql); `
and I also tried 
`String sql ="UPDATE sobereno set datumvreme='"+links+"',websajt='"+html+"',zbor='"+Text+"'";
         stmt.executeUpdate(sql); `
and
` 	try{
 		
 		String query = "insert into sobereno";
 		rs = st.executeQuery(query);
 		System.out.println("Records from Database");
 		while(rs.next()){
 			String datumvreme = rs.getString("datumvreme");
 			String websajt = rs.getString("websajt");
 			String zbor = rs.getString("zbor");
 			System.out.println("datumvreme: "+datumvreme+"    "+"websajt: "+websajt + "     "+"zbor: "+zbor);
 		}`
Cant manage to make it work.

**Comment by justusual** [comment]
I am desperate

**Comment by rzo1** [comment]
Could you tell us your database schema, e.g. the SQL create statement of your table? 

From your answer I can only see, that you have a table called `sobereno` with the columns `datumvreme`, `websajt`, `zbor`? What are the data types of your columns? I guess, that `datumvreme` is an SQL timestamp, `websajt` and `zbor` of type varchar?`

Do you receive any kind of stacktrace while running your code?

**Comment by justusual** [comment]
Yes you got that right about the table and the columns. When I run the program it just returns that I have recorded data in the database. but nothing. no data there

**Comment by rzo1** [comment]
-  Debugging your code would be the best choice in order to find the potential issue
- Go for an approach using `PreparedStatements`. Declare an attribute in your class of type `PreparedStatement` and initialize it in the constructor via `connection.prepareStatement(sql)` where `sql` is your SQL insert statement like `INSERT INTO sobereno VALUES0 (?,?,?)`. This assumes, that you do not have a surrogate primary key in your table (if you want a numeric primary key, you could obtain it from a Postgres sequence)

- With this prepared statement you can go for inserting tuples to your database. Note well, that using JDBC [batch mode](http://www.tutorialspoint.com/jdbc/jdbc-batch-processing.htm) will give you a slight performance boost.

```
                insertKeyStatement.setTimestamp(1, new Timestamp(new java.util.Date().getTime()));
                insertKeyStatement.setString(2, html);
                insertKeyStatement.setString(3, text);
                insertKeyStatement.executeUpdate();        
```

-  Retrieving the stored values can be done via:

```
            ResultSet result = connection.createStatement().executeQuery("select * from sobereno");
            while(result.next()) {
                Timestamp datumvreme = rs.getTimestamp("datumvreme");
                String websajt = rs.getString("websajt");
                String zbor = rs.getString("zbor");
                System.out.println("datumvreme: "+datumvreme+"    "+"websajt: "+websajt + "     "+"zbor: "+zbor);
            }
                
```

**Comment by justusual** [comment]
I am still having trouble, this is my my code database+mycrawler

`import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import com.sleepycat.je.utilint.Timestamp;

public class Databaza extends MyCrawler {
	
	  public static Connection getConnection() throws Exception {
			try {

				Class.forName("org.postgresql.Driver");

			} catch (ClassNotFoundException e) {

				System.out.println("Where is your PostgreSQL JDBC Driver? "
						+ "Include in your library path!");
				e.printStackTrace();
				return null;

			}

			Connection connection = null;

			try {

				connection = DriverManager.getConnection(
						"jdbc:postgresql://192.168.178.194:5432/kolekcija", "postgres",
						"postgres");

			} catch (SQLException e) {

				System.out.println("Connection Failed! Check output console");
				e.printStackTrace();
				return connection;

			}

			if (connection != null) {
				System.out.println("You made it, take control your database now!");
			} else {
				System.out.println("Failed to make connection!");
			}
			return connection;
		}


	  	public static void main(String[] args) throws Exception {
		    Connection conn = null;
		    PreparedStatement pstmt = null;
		    PreparedStatement insertKeyStatement;
		    try {
		      conn = getConnection();
		      String query = "insert into sobereno(datumvreme, websajt, zbor) values(?, ?, ?)";
		   
	    //	    pstmt = conn.prepareStatement(query);
		//      pstmt.setTimestamp(1, "datumvreme"); 
		 //     pstmt.setString(2, "html"); 
		  //    pstmt.setString(3, "text");
		      
		      insertKeyStatement.setTimestamp(1, new Timestamp(new java.util.Date().getTime()));
              insertKeyStatement.setString(2, html);
              insertKeyStatement.setString(3, text);
              insertKeyStatement.executeUpdate(); 

		  //    pstmt.executeUpdate(); // execute insert statement
		    } catch (Exception e) {
		      e.printStackTrace();
		    } finally {
		      pstmt.close();
		      conn.close();
		    }
		  }
		}
`
`import java.util.Set;
import java.util.regex.Pattern;

import edu.uci.ics.crawler4j.crawler.Page;
import edu.uci.ics.crawler4j.crawler.WebCrawler;
import edu.uci.ics.crawler4j.parser.HtmlParseData;
import edu.uci.ics.crawler4j.url.WebURL;

public class MyCrawler extends WebCrawler {

  

	private final static Pattern FILTERS = Pattern.compile(".*(\\.(css|js|gif|jpg"
                                                           + "|png|mp3|mp3|zip|gz))$");

    /**
     * This method receives two parameters. The first parameter is the page
     * in which we have discovered this new url and the second parameter is
     * the new url. You should implement this function to specify whether
     * the given url should be crawled or not (based on your crawling logic).
     * In this example, we are instructing the crawler to ignore urls that
     * have css, js, git, ... extensions and to only accept urls that start
     * with "http://www.ics.uci.edu/". In this case, we didn't need the
     * referringPage parameter to make the decision.
     */
     @Override
     public boolean shouldVisit(Page referringPage, WebURL url) {
         String href = url.getURL().toLowerCase();
         return !FILTERS.matcher(href).matches()
                && href.startsWith("http://www");
     }

     /**
      * This function is called when a page is fetched and ready
      * to be processed by your program.
      */
     @Override
     public void visit(Page page) {
         String url = page.getWebURL().getURL();
         System.out.println("URL: " + url);

         if (page.getParseData() instanceof HtmlParseData) {
             HtmlParseData htmlParseData = (HtmlParseData) page.getParseData();
             String text = htmlParseData.getText();
             String html = htmlParseData.getHtml();
             Set<WebURL> links = htmlParseData.getOutgoingUrls();

             System.out.println("Text length: " + text.length());
             System.out.println("Html length: " + html.length());
             System.out.println("Number of outgoing links: " + links.size());
             System.out.println("Text: " + text);

             
         }
    }
}`

**Comment by justusual** [comment]
I still need help with this :)

**Comment by rzo1** [comment]
I implemented a little example: [crawler4j-postgres-sample](https://github.com/rzo1/crawler4j-postgres-sample)

**Comment by rzo1** [comment]
Maybe we can close this @yasserg - seems to be solved.
