### ISSUE TITLE
How to control number of URLs crawled per domain? 

### ISSUE THREAD

**Issue by sachinmakasana** [yasserg/crawler4j#146]
maxUrlsToFollow and MaxPagesToFetch both seems to affect TOTAL number of pages and urls, not per domain. so is there any way to control number of pages per domain?

**Comment by Chaiavi** [comment]
Not in the basic configuration.

You can try a hack, by counting the number of pages taken from a specific
domain, and when you reach your limit then you can put the domain name in a
pre-defined variable or collection which the shouldVisit() method checks
and if it sees that domain then it will return false.
