### ISSUE TITLE
[Question] How to modify should visit URL?

### ISSUE THREAD

**Issue by phamptu** [yasserg/crawler4j#148]
I need to crawl an Js generated site, so I can use rendering service to get generated web page like: splash.readthedocs.io
For example, if should visit url is : `www.a.com/b.html`, i want to change it to url from splash: 
`x.x.x.x:8250?render=www.a.com/b.html`, then visit function will process result of `x.x.x.x:8250?render=www.a.com/b.html`
I know that I can use `this.myController.addSeed(modifiedUrl)` direct from my Crawler class? Are there any better way ?

**Comment by nkaraman** [comment]
Yes, you can make your rendering service with build in http-proxy and add to configs of Crawler4J this proxy.

**Comment by rzo1** [comment]
- Check this part of the `WebCrawler` class:

```
  /**
   * This function is called before processing of the page's URL
   * It can be overridden by subclasses for tweaking of the url before processing it.
   * For example, http://abc.com/def?a=123 - http://abc.com/def
   *
   * @param curURL current URL which can be tweaked before processing
   * @return tweaked WebURL
   */
  protected WebURL handleUrlBeforeProcess(WebURL curURL) {
    return curURL;
  }
```

- Another option: You could take a modified `PageFetcher` into consideration (see https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java) in which you add the  appropriate URL part of your render engine. This modification should be of simple nature.

**Comment by s17t** [comment]
Closing.
