### ISSUE TITLE
duplicate imports in CrawlController

### ISSUE THREAD

**Issue by mbohun** [yasserg/crawler4j#156]
i guess you first cleaned up/moved imports:
https://github.com/yasserg/crawler4j/commit/6ffe56b42c2b045c856455ca21302bbce5e38b0c

then you did a merge, and pulled the moved imports back in, ending up with duplicates:
https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java#L20-L25

and

https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java#L39-L44

**Comment by rzo1** [comment]
I guess this is fixed?  @yasserg Can you close it?
