### ISSUE TITLE
cannot run even a basic sample

### ISSUE THREAD

**Issue by soq2000** [yasserg/crawler4j#162]
Dear all,
I just run the basic sample, and the crawler does not give me any URL. I saw in the download directory some data but no log information at all. Please guide me.
I use the org.apache.logging.log4j instead of org.slf4j. Can it cause the above problem?
BR

**Comment by MichaelWey** [comment]
Maybe, U can download slf4j dependency from http://www.slf4j.org/dist/slf4j-1.7.21.zip.  I use it and run the basic sample successfully .Try it again. Good luck!

**Comment by soq2000** [comment]
Thanks MichaelWey.
In fact the problem was that the JRE I used was 1.5. A version > 1.7 is neccessary. I just figured it out by chance: I copied the code into my App and then the compiler just complained :-).

**Comment by MichaelWey** [comment]
congratulations，you are welcome!

**Comment by soq2000** [comment]
Dear all,
I am back for the same incident. After modifying my app for other feature, when I recalled the crawling feature, it does not work any more, The thread somehow stops at this line in the run() function of the class WebCrawler:        
frontier.getNextURLs(50, assignedURLs);
 
and throw uncatch Exception
Any hints please
Many thanks

**Comment by rzo1** [comment]
Just provide the related stacktrace.

**Comment by s17t** [comment]
Please update to 4.4.0 (which requires Java8). There various examples in the `crawler4j-examples` subfolder.
