### ISSUE TITLE
Crawler4j downloads full content before checking content type

### ISSUE THREAD

**Issue by santiquetzal** [yasserg/crawler4j#163]
Hello,

I'm using crawler4j to retrieve only `"text/html"` pages. 

I don't want binary data, so I let CrawlConfig use the default values (false) for `includeBinaryContentInCrawling` and `processBinaryContentInCrawling.`

But... I found a problem: If I try to download a binary file, for example: http://central.maven.org/maven2/org/apache/commons/commons-compress/1.12/commons-compress-1.12.jar, the following actions are done:

**WebCrawler class** executes `processPage(...`) method, there:

**1. Line 323**: Call to PageFetcher: 
- `fetchResult = pageFetcher.fetchPage(curURL);`
-  PageFetcher creates a **HttpGet request** and executes it obtaining the response **Header** and **part of the desired file**.
- Note: I think a HttpHead will be a more appropiate request (because by now we don't know if we are interestend in the file content).

**2 - Line .385**: If status code is 200: A **call to FetchResult is done** to get page content.
- `page.load(entity)` downloads the file. **Why is downloading the file?** We don't know if we are interested on it by now!.
- `page.setFetchResponseHeaders(responseHeaders)` stablish responseHeaders.

**3 - L.385:** After retrieving the file a call to the Parser is made
- `parser.parse(page, curURL.getURL());` The parser checks: 
- The content type is Binary (or other, but I'm focusing on binary case)
  `If config.isIncludeBinaryContentInCrawling() == false => throw new NotAllowedContentException();`
- This makes a NotAllowedContentException is thrown, so the file will be not visited by WebCrawler (Or a overrided webCrawler method).

**So... If I don't want to store binary files... Why its content is downloaded?**

Can you check that the problem I found is really happening, or I'm doing something incorrectly?
I capture network traffic and I can see that the binary files were retrieved althougth the config of the crawler `has includeBinaryContentInCrawling = false`

I fix it overriding some methods: 
(I prefer not to modify original code, but if I did I think I could find a cleaner solution):

```
I created a Class that extends PageFetcher:

public class PageFetcherExt extends PageFetcher {

    public PageFetcherExt(CrawlConfig config) {
        super(config);

    }

    @Override
    public PageFetchResult fetchPage(WebURL webUrl) throws InterruptedException, IOException, PageBiggerThanMaxSizeException {
        String toFetchURL = webUrl.getURL();

        PageFetchResult fetchResult = new PageFetchResult();
        HttpHead head = null;
        try {
            head = new HttpHead(toFetchURL);

            synchronized (this.mutex) {
                long now = new Date().getTime();
                if (now - this.lastFetchTime < this.config.getPolitenessDelay()) {
                    Thread.sleep(this.config.getPolitenessDelay() - (now - this.lastFetchTime));
                }
                this.lastFetchTime = new Date().getTime();
            }

            HttpResponse response = this.httpClient.execute(head);
            fetchResult.setEntity(response.getEntity());
            fetchResult.setResponseHeaders(response.getAllHeaders());
            fetchResult.setFetchedUrl(toFetchURL);
            fetchResult.setStatusCode(response.getStatusLine().getStatusCode());

            String contentType = response.containsHeader("Content-Type") ? response.getFirstHeader("Content-Type").getValue() : null;
            String typeStr = (contentType != null) ? contentType.toLowerCase() : "";

            if (typeStr.equals("") || (typeStr.contains("text") && typeStr.contains("html"))) {
                return super.fetchPage(webUrl);
            } else {
                return fetchResult;
            }
        } finally {
            if (head != null)
                head.abort();
        }

    }
```

In my CrawlerController class: 
`PageFetcher pageFetcher = new PageFetcherExt(config);`

This makes that if a file is not `"text/html"` a Generic Exception ("Exception while fetching content for: {} [{}]") is thrown. 
The appropiate exception should be NotAllowedContentException, but I prefer not to change original code, so I am unable to add this exception to the method.

I have captured my network traffic and I could see that the full file was downloaded with original code and now the file content is only downloaded when the content type is not "text/html".

Notice that now I always send a HttpHead request, and I let the crawler make a HttpGet only it content type is "text/html" (This duplicates the number of requests for valid types, but avoids downloading undesired content)

**Comment by haoshen** [comment]
A very elegant solution , although I may change the origin code.

**Comment by s17t** [comment]
The base PageFetcher should depends upon a structure holding the logic but for now in 98aaa96 an example with @santiquetzal code and little test with WireMock.
