### ISSUE TITLE
Skipping url StatusCode 503

### ISSUE THREAD

**Issue by nhasemann** [yasserg/crawler4j#165]
I'm trying to crawl amazon and I start with the main page (www.amazon.de). Now following error occurs:

17:01:39 WARN  [Crawler 1] - [WebCrawler]- Skipping URL: https://www.amazon.de/, StatusCode: 503, text/html, Service Unavailable

Do you have any idea how I can fix that?

**Comment by Chaiavi** [comment]
Try changing your crawler's user agent to something Amazon might recognize
- maybe that is the problem

**Comment by nhasemann** [comment]
thanks with my user agent it works.

**Comment by Chaiavi** [comment]
My Pleasure


@yasserg this issue can be closed
