### ISSUE TITLE
Project being maintained?

### ISSUE THREAD

**Issue by JCotton1123** [yasserg/crawler4j#170]
Hi, there are 70 issues and 30 PRs currently open on this project. Is it still being maintained?

**Comment by s17t** [comment]
@yasserg Do you need hand in maintain the library / pull request ?

**Comment by yasserg** [comment]
I don't really have the time to maintain this project anymore.

**Comment by JCotton1123** [comment]
@yasserg Understood. Would you be open to granting a few of us commit us so we can maintain it?

**Comment by s17t** [comment]
@yasserg no problem, please just allow others to push maintenance and development forward. I would like to because I am using this library in active project. Thank you.

**Comment by rzo1** [comment]
We are using this library too in our projects (like @s17t )

**Comment by s17t** [comment]
@rzo1 I have asked a namespace to sonatype already but I would prefer not using my own  fork. I contacted @yasserg on LinkedIn. Let's see...

**Comment by rzo1** [comment]
Yup - let's wait :) thx for response

**Comment by yasserg** [comment]
Ok, I can add some of you as committers. The challenge that I have had with pull requests has been that many random pull requests are submitted that are only relevant to very specific use cases or not high quality. Please go over some of the current pull requests and post your comments there why/if they should be merged or rejected or if updates are needed. Alternatively you can also submit your own pull requests if any.

**Comment by s17t** [comment]
@yasserg thank you for your kind reply. Just to cite some of PRs: #58 #78, the good part of  #79 and the idea of #145 is good but I agree that implementation is too specific: maybe just providing right interfaces around frontiers would allow people to implements their own solution.

**Comment by yasserg** [comment]
@s17t I added you as committer. Please start with cleaning up #58 and get it merged. It needs some checkstyle fixes.

**Comment by MadEgg** [comment]
I'm still here ;-) I've moved along quite far from the main branch in development, because pull requests weren't accepted here I stopped bothering with creating the pull requests. I'd still prefer a central repository where development is centered so if this is being picked up again, I'd be more than happy to contribute more pull requests.

I have done a major overhaul of the queue system (slightly related to #145 but very different - it offers enormous improvements in parallel crawling. At least in my situation. Anyway, if you let me know what's wrong with #58 - I can probably improve it.

**Comment by s17t** [comment]
@yasserg I would like to create a release. Have any hint on how create a release for maven central ? Do you have credentials for sonatype ? Thank you.

**Comment by onebeartoe** [comment]
@s17t @yasserg I setup a build job for snapshots, but it is currently failing.

It is located here: 

https://onebeartoe.ci.cloudbees.com/job/crawler4j/

I realize this is not Maven Central, but at least gives access to snapshots.

The repository to add to the POM is 

https://repository-onebeartoe.forge.cloudbees.com/snapshot/

At this point, are the 'semicolon missing' and other errors expected?  Maybe I am missed something.

**Comment by s17t** [comment]
@onebeartoe thank you. The problem seems to be [this one](http://stackoverflow.com/questions/24403298/netbean-error-missing-semicolonjava-comment).

**Comment by s17t** [comment]
@onebeartoe the build now pass but dies later

https://onebeartoe.ci.cloudbees.com/job/crawler4j/5/console

**Comment by onebeartoe** [comment]
@s17t Okay cool.  I removed Sonar coverage, until I figure out why it failed.

But the build is good now.

**Comment by s17t** [comment]
Added the repository in the README. Thanks again @onebeartoe

**Comment by s17t** [comment]
Paging @yasserg again about information on release process.

**Comment by s17t** [comment]
Paging @yasserg again for information on release process.

**Comment by yasserg** [comment]
If a release is needed I will need to that (it requires my user/pass). Has there been enough important changes since last release that deserve a new release?

**Comment by s17t** [comment]
I marked [all PR closed after 2015-12-03](https://github.com/yasserg/crawler4j/pulls?page=1&q=is%3Apr+closed%3A%3E2015-02-03&utf8=%E2%9C%93) with 4.3 milestone. They are mostly small changes and bug fixing but since this library is actually used in real world many people would benefit.

**Comment by s17t** [comment]
I close this ticket since there is at least one more developer (me) allowed to push artifact on maven central. If any of the others committers are willing to do so just ask permission in sonatype's ticket [0] and follow standard maven release procedure.

[0] https://issues.sonatype.org/browse/OSSRH-1800
