### ISSUE TITLE
Img tags not being crawled

### ISSUE THREAD

**Issue by jbfbell** [yasserg/crawler4j#176]
I have set the setIncludeBinaryContentInCrawling property to true but the img src urls are not being crawled.

**Comment by s17t** [comment]
Hello, would you mind to give us the URL you have tried to crawl ? If it is not a public page could you paste the HTML in a gist or in a pastebin ? 

Which version of jcrawler are you using ?

**Comment by rzo1** [comment]
How does your `shouldVisit` looks like?

**Comment by jbfbell** [comment]
@rzo1 thank you, I think there was a bad condition in my shouldVisit, sorry for the inconvienence
