### ISSUE TITLE
fail to use jpa

### ISSUE THREAD

**Issue by xiangtianyu** [yasserg/crawler4j#179]
Hi, everyone.
My proect is relied on springboot and i try to use jpa to connect to db.

`public interface ChapterDao extends CrudRepository<Chapter, Long> {
    List<Chapter> findAll();
}`
i delare a private var in my crawler which extends WebCrawler
`@Autowired
    private ChapterDao chapterDao;`
and i try to use`chapterDao.save()`to save data that i get from websites,but there are something wrong,chapterDao is always null,and i don't know why.
Do you have an idea what's the problem?

**Comment by s17t** [comment]
Hello, without reading the code is hard to help you. Are you sure your crawler is in the Spring context path? Did you annotated your class with `@Configuration` (or `@Service`) ?

**Comment by rzo1** [comment]
For Spring integration you need to implement:

```
 public interface WebCrawlerFactory<T extends WebCrawler> {
        T newInstance() throws Exception;
    }
```

and then let Spring create the WebCrawler instances. Otherwise the injection will not work properly.

However, we need more code fragments to help you properly...

**Comment by xiangtianyu** [comment]
Thanks for rzo1's resolution.I implement WebCrawlerFactory and send chapterDao as an argument and it works!
