### ISSUE TITLE
Run callback inside WebCrawler visit function?

### ISSUE THREAD

**Issue by arsenik** [yasserg/crawler4j#180]
In my WebCrawler I would like to execute an anonymous function which is created when adding the seed. 

Is there any way of having access to a callback inside WebCrawler visit function?

**Comment by s17t** [comment]
You can simple subclass WebCrawler and override visit method as [described in main page](https://github.com/yasserg/crawler4j#quickstart).

**Comment by arsenik** [comment]
With each url I want to parse, I also have additional data.
```
String url_to_parse = "http://www.ics.uci.edu/~lopes/";
String url_additionnal_data = "XXXX";
```

When I add seed, I would like to pass these additional data.
```
controller.addSeed(url_to_parse);
```

So I can have access to url_additionnal_data in thread of public void visit(Page page). 

How would you extends?

**Comment by s17t** [comment]
You can implement `WebCrawlerFactory`
```java
public class CrawlerControllerFactory implements CrawlController.WebCrawlerFactory {

    @Override
    public WebCrawler newInstance() {
          return new MyCrawler(
                complexDataHoldingSeedsMetadata);
    }
}
```
and then to use that factory:
```java
CrawlerControllerFactory factory = new CrawlerControllerFactory(complexDataHoldingSeedsMetadata);
controller.startNonBlocking(factory, numberOfCrawlers);
```

In the `MyCrawler`:
```java
public class MyCrawler extends WebCrawler {

   public MyCrawler(Whatever complexDataHoldingSeedsMetadata) {
    ...
   }

    @Override
    public boolean shouldVisit(Page referringPage, WebURL url) {
      ...
    }
} 
```

**Comment by arsenik** [comment]
+1
