### ISSUE TITLE
Is crawler4j support xpath

### ISSUE THREAD

**Issue by hendisantika** [yasserg/crawler4j#183]
I want to ask again.
Is crawler4j support xpath?

If it is yes. How to use xpath on crawler4j?

Thanks

**Comment by Chaiavi** [comment]
I am not sure I understand the question.

But, when using the crawler you get the crawled pages at the "visit()"
function.

You can take the html from there and do whatever you want with them, so you
can parse them with xpath or whatever.


Does that answer your question ?

**Comment by hendisantika** [comment]
Give me the example please.

The way to extract the web page content using xpath.

Thanks

**Comment by Chaiavi** [comment]
Sorry, I don't have the time.

But you can see at the instructions on the main page on github.


Check out the visit() method.

You will see something which gets the HTML


Do whatever action on that html

**Comment by s17t** [comment]
Hi @hendisantika, in the README there is a good coverage of crawler4j usage. Start from [here](https://github.com/yasserg/crawler4j#quickstart).

In the visit() method you can call whatever library you want to use xpath expression and retrieve information from Page.

Closing.

**Comment by hendisantika** [comment]
The readme does not cover the way to to extract the data from web pages. It is just said about print link from the web page.
