### ISSUE TITLE
Error: "Can't call Database.get: Database was closed."

### ISSUE THREAD

**Issue by silentbang** [yasserg/crawler4j#186]
I'm creating a new instance of CrawlController everytime there's a request (my application is web based). When the 1st request's finished, the crawlers're stopped.

> [Thread-4] INFO  e.u.i.c.crawler.CrawlController -
				It looks like no thread is working, waiting for 10 seconds to make sure...
[Thread-4] INFO  e.u.i.c.crawler.CrawlController -
				No thread is working and no more URLs are in queue waiting for another 10 seconds to make sure...
[Thread-4] INFO  e.u.i.c.crawler.CrawlController -
				All of the crawlers are stopped. Finishing the process...
[Thread-4] INFO  e.u.i.c.crawler.CrawlController -
				Waiting for 10 seconds before final clean up...

When the 2nd request's triggered, I got this error:
`[http-nio-9000-exec-3] ERROR e.u.i.crawler4j.frontier.DocIDServer -
				Exception thrown while getting DocID
java.lang.IllegalStateException: Can't call Database.get: Database was closed.
	at com.sleepycat.je.Database.checkOpen(Database.java:1863)
	at com.sleepycat.je.Database.get(Database.java:1000)
	at edu.uci.ics.crawler4j.frontier.DocIDServer.getDocId(DocIDServer.java:77)
	at edu.uci.ics.crawler4j.crawler.CrawlController.addSeed(CrawlController.java:409)
	at edu.uci.ics.crawler4j.crawler.CrawlController.addSeed(CrawlController.java:381)`

My guess is that I need a CrawlConfig for every request. Is it true?

**Comment by s17t** [comment]
Yes, it is true. The closing operation is terminal for the underlying embedded database. The sub optimal is to create a CrawlConfig per request having care to customize the DB storage path with `CrawlConfig.setCrawlStorageFolder` with different folder for every request.

My guess is that probably you need to decouple the webrequests from the crawling stage with a queue or a buffer but a start a CrawlConfig per request should work.

**Comment by silentbang** [comment]
Thank you. I tried and it worked. If I use one crawlStorageFolder location for all of the requests, does it sound appropriate?

**Comment by s17t** [comment]
I honestly don't know but I would avoid for precaution. Maybe @yasserg can answer your late question. In alternative you could write some test.

**Comment by Jacksonary** [comment]
hi, @duc-anh-tran @s17t  I got same exception when I set number of crawlers more than 1 ,  detail of Exception as follows: 

```log
11:15:51.416 [Crawler 1] ERROR [DocIDServer.java:78] - Exception thrown while getting DocID
java.lang.IllegalStateException: Can't call Database.get: Database was closed.
	at com.sleepycat.je.Database.checkOpen(Database.java:2133)
	at com.sleepycat.je.Database.get(Database.java:1273)
	at edu.uci.ics.crawler4j.frontier.DocIDServer.getDocId(DocIDServer.java:75)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:481)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:306)
	at java.lang.Thread.run(Thread.java:748)
```

and before it ，I found log like this: 

```log
11:15:41.408 [Thread-46] INFO  [CrawlController.java:314] - All of the crawlers are stopped. Finishing the process...
11:15:41.409 [Thread-46] INFO  [CrawlController.java:325] - Waiting for 10 seconds before final clean up...
```
