### ISSUE TITLE
Allow terminating all running threads from WebCrawler.shouldVisit()?

### ISSUE THREAD

**Issue by silentbang** [yasserg/crawler4j#194]
Hi,
I'm just thinking if we could limit the number of pages which are considered valid (in shouldVisit) for each crawl session. As the MAX_PAGE_TO_FETCH does not satisfy that need, it only limit the number of pages to fetch whether they're valid or not.
Is there any way to send SHUTDOWN signal from WebCrawler class? so that if it reaches a specified limit of valid pages it will terminate the session?

**Comment by dariusgm** [comment]
Have you thought about a timebased approach? Cancel every Crawler Thread after a fixed time?

or you could save the current page count in a third party application and check in every shouldVisit if the limit was reached or not. I would implement it using redis, as it allows an atomic increment from multiple threads. Jedis is a very nice Java Client for redis.

**Comment by silentbang** [comment]
Yes I did. However, it does not satisfy my requirement. As my website is given 75000 query limit per hour only. 
As for the saving of current page count, I did a research and decided to use AtomicInteger in Java for thread safe. It's not really an issue but the sending SHUTDOWN signal capability.

**Comment by dariusgm** [comment]
You could try to call https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java#L531 inside your WebCrawler implementation after the given amount of WebPages to force the shutdown.

**Comment by silentbang** [comment]
Thanks dariusgm. You're right, I start a thread to constantly check whether it exceeds limit and make a call to CrawlController.shutdown() successfully.
