### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by codycoggins** [yasserg/crawler4j#200]
Does crawler4j support SSL in its current state?  We are using crawler4j version 4.2.  

To enable SSL do I need to do any preparatory work in the environment, such as setting up a keystore?

Or alternately add classes such as this solution: (which I can't get to compile)
http://stackoverflow.com/questions/24658634/crawler4j-not-working-for-https-urls

This is the error/stack dump that I am getting:
`
[err] [Crawler 1] WARN edu.uci.ics.crawler4j.crawler.WebCrawler - Unhandled exception while fetching https://www.google.com/: https protocol is not supported
[err] [Crawler 1] INFO edu.uci.ics.crawler4j.crawler.WebCrawler - Stacktrace: 
[err] org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
[err] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:108)
[err] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[err] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[err] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[err] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[err] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
[err] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[err] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[err] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
[err] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
[err] 	at edu.uci.ics.crawler4j.fetcher.PageFetcher.fetchPage(PageFetcher.java:237)
[err] 	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:323)
[err] 	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:274)
[err] 	at java.lang.Thread.run(Thread.java:745)
`

Thanks for your help

**Comment by codycoggins** [comment]
Resolved by setting **config.setIncludeHttpsPages**.
`
CrawlConfig config = new CrawlConfig();
config.setIncludeHttpsPages(true);
//other configs
PageFetcher pageFetcher = new PageFetcher(config);
// ...
controller = new CrawlController(config, pageFetcher, robotstxtServer);
`

**Comment by Chaiavi** [comment]
Thank you for leaving the solution here for future reference of other users.
