### ISSUE TITLE
Is the `visit` method thread safe?

### ISSUE THREAD

**Issue by knoxxs** [yasserg/crawler4j#203]
In the following example:

> [Collecting data from threads](https://github.com/yasserg/crawler4j/tree/master/src/test/java/edu/uci/ics/crawler4j/examples/localdata): this example demonstrates how the controller can collect data/statistics from crawling threads.

The code is incrementing the linksVisited count but it should be thread safe. Am I right?

**Comment by rzo1** [comment]
Every crawler (= thread) is incrementing it's own `CrawlStat` object.
