### ISSUE TITLE
a Problem about fetchContent() in Downloader.java

### ISSUE THREAD

**Issue by HuangZhenyang** [yasserg/crawler4j#204]
This function is in crawler4j/src/test/java/edu/uci/ics/crawler4j/examples/localdata/Downloader.java
I downloaded your code of Downloader.java, and wanted to run it in eclipse. However, eclipse tells me that 

> The method fetchContent(Page) in the type PageFetchResult is not applicable for the arguments (Page, int)

Here is the code (in line 67):
`fetchResult.fetchContent(page, pageFetcher.getConfig().getMaxDownloadSize());` 

Could you please help me? Thank you.

**Comment by s17t** [comment]
Are you sure you checkout latest revision ? In master the line 67 has an ['else' statement](https://github.com/yasserg/crawler4j/blob/635a5cf4fcaecce23f42d598446d937426ca760d/src/test/java/edu/uci/ics/crawler4j/examples/localdata/Downloader.java#L67).

**Comment by HuangZhenyang** [comment]
Er... I am sorry that line 67 is in my local project....
It seemed that something was wrong with my jar of Log... When I  annotated the log sentences, it worked!
Thank u for replying!

**Comment by s17t** [comment]
You are welcome!
