### ISSUE TITLE
Order Set<WebURL> links

### ISSUE THREAD

**Issue by nhasemann** [yasserg/crawler4j#206]
First of all, I would like to compliment all developers for this project.

I'm crawling a website with recommendations and for me it is necessary that the entries WebURL in the data structure Set "link" have the same order as occur in the web page.

edu.uci.ics.crawler4j.crawler.examples BasicCrawler.java

`Set<WebURL> links = htmlParseData.getOutgoingUrls();`

Is there any possibility how I can implement this?

**Comment by Chaiavi** [comment]
I assume it is currently a set and not a list in order not to get
duplicates (as we sites might have the same link several time on the same
page)

**Comment by bgoldowsky** [comment]
Try defining your own variant of the Parser class, and where it says
`   TextParseData parseData = new TextParseData();`
add:
`   parseData.setOutgoingUrls(new LinkedHashSet<>());`

LinkedHashSet, unlike plain HashSet, will keep track of the order that elements were added and give them back in the same order.

Haven't tried this, but it seems like it should work.

**Comment by nhasemann** [comment]
Thank you so much. It does work with a LinkedHashSet.
