### ISSUE TITLE
How to change logging level?

### ISSUE THREAD

**Issue by marcogerosa** [yasserg/crawler4j#207]
While executing the crawler, it sends a lot of DEBUG level messages to the console. I've tried to override the configuration of Log4J using a log4j.xml in my projects, but it did not work, it keeps sending the DEBUG msg do the console. It seems that somehow crawler4j has its own configuration.

**Comment by Chaiavi** [comment]
it is using slf4j and logback

**Comment by HunterSherms** [comment]
@marcogerosa adding the following to /src/main/resources/logback.xml should do the trick

```xml
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info"><!-- hush! -->
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

**Comment by marcogerosa** [comment]
ok, it worked. Thank you

**Comment by CesarCoelho** [comment]
Hi,
It seems that this is a common request. Can you make it part of the README?
Thanks!
