### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by mydearQI** [yasserg/crawler4j#212]
how to simulate login?like login into [www.zhihu,com](www.zhihu.com)

**Comment by lumyus** [comment]
AuthInfo authInfo = new FormAuthInfo(String username, String password, String loginUrl, String usernameFormStr, String passwordFormStr);
config.addAuthInfo(authInfo);

**Comment by mydearQI** [comment]
thank you

**Comment by sagar441989** [comment]
@mydearQI has it worked for you?

**Comment by mydearQI** [comment]
e,i think it should be OK,however ,i  haven't tried it

**Comment by mxphu** [comment]
How to simulate a login, if the login action requires some more session parameters (not only username and password)?
For example, when I log in a Website based on Drupal, I have to send 5 parameters to the server:
- the username and the password
- 3 session keys: I have to take them from hidden fields in the login page source code

Do you have idea for this case?
Thanks in advance
