### ISSUE TITLE
More flexible form authentication

### ISSUE THREAD

**Issue by JCotton1123** [yasserg/crawler4j#214]
Hi, would you be receptive to a few modifications to the FormAuth class to allow an arbitrary map of fields to be supplied instead of just a username/password? A number of login forms require additional fields like CSRF tokens or an organization name. These features are probably common enough to build the functionality into the FormAuth class. Thoughts?

**Comment by Chaiavi** [comment]
Makes sense.

**Comment by mxphu** [comment]
Hi, I have the same wonder here. Did you have solution?
Thanks
