### ISSUE TITLE
Sleepycat dependency?

### ISSUE THREAD

**Issue by StephanSchmidt** [yasserg/crawler4j#221]
Hello,

looks like the sleepycat dependency needs to be gotten from Oracle Maven repo. 

1. Any alternatives?
2. If the case, should this be in README.md?

Thanks,
Stephan

**Comment by Chaiavi** [comment]
Sleepycat is embedded into C4J as the internal db.

It is in heavy use as an in-memory DB of C4J.


Currently there are no alternatives.

**Comment by StephanSchmidt** [comment]
@Chaiavi Thanks, no alternatives to Sleepycat or no alternative repo?

**Comment by s17t** [comment]
Implement an abstraction for URL repository is the next little big thing, there was a proposition #145 to migrate from Barkley to Redis but was too invasive. Please feel free to propose a refactoring to separate repository and implemention (with test!).

**Comment by hwellmann** [comment]
Users should be warned that Sleepycat has a copyleft license. 

So anybody distributing crawler4j (and thus Sleepycat) in their product is forced by the Sleepcat license to distribute the sources of their products.

**Comment by rzo1** [comment]
@s17t I added a first draft here: https://github.com/rzo1/crawler4j/tree/modularization-branch
Maybe you can take a look at it. I also added you as a contributor, so we can remove the hard dependency to get a more flexible approach for custom Frontier/DocIDServer implementations.

**Comment by pgalbraith** [comment]
The current Sleepycat license seems to be Apache 2.0:

https://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/jeoslicense-086837.html

Perhaps just a version update will solve the license problem?

**Comment by s17t** [comment]
I bumped up the version of sleepycat to latest. I missed that it is now Apache 2 complaint. I close this issue.

> To abstract out the IO portion, I'd like to see a solution that has a single DAO interface, where the IO implementation is injected into the controller.

Agree. IoC and interface is the way.
