### ISSUE TITLE
Number of Crawlers

### ISSUE THREAD

**Issue by vwangworawut** [yasserg/crawler4j#224]
The amount of crawlers are not being utilized. For example, when I set the number of crawlers to 20, only 2-4 are being shown crawling on the console. Why is that?

**Comment by s17t** [comment]
Hi,
 running `edu.uci.ics.crawler4j.examples.basic.BasicCrawlController` with 20 thread will run and show all thread running. Would you provide more information about your configuration and use case ?

**Comment by Quix0r** [comment]
It depends on many factors, like how broad (many different hosts, you don't want to turn crawl4j into a DoS tool) the crawl is. If you have lesser starting URLs, sure your crawl is slow at the beginning. If you stay within that URLs, it remains slow as crawl4j has some politeness implemented, not to send to much requests per second to a single host (no DoS tool intended).

Next is, how many external (and if your code logic allows them) sites are linked, the more you have, the more can be crawled simultanously at the same time.
