### ISSUE TITLE
Links for examples in project description not working

### ISSUE THREAD

**Issue by clennpillo** [yasserg/crawler4j#240]
Hi,

When I clicked the links of examples, it respond me 404 not found, what am i supposed to do if i want to read those examples ?

This is the links I clicked, see below pasted from project description
---
Basic crawler: the full source code of the above example with more details.
Image crawler: a simple image crawler that downloads image content from the crawling domain and stores them in a folder. This example demonstrates how binary content can be fetched using crawler4j.
Collecting data from threads: this example demonstrates how the controller can collect data/statistics from crawling threads.
Multiple crawlers: this is a sample that shows how two distinct crawlers can run concurrently. For example, you might want to split your crawling into different domains and then take different crawling policies for each group. Each crawling controller can have its own configurations.
Shutdown crawling: this example shows have crawling can be terminated gracefully by sending the 'shutdown' command to the controller.
Postgres/JDBC integration: this shows how to save the crawled content into a Postgres database (or any other JDBC repository).

**Comment by s17t** [comment]
Hi, links to examples should now work again ( #241 )
