### ISSUE TITLE
Binary Content Crawling

### ISSUE THREAD

**Issue by hkasera** [yasserg/crawler4j#249]
Hello,

I would like to post a suggestion for Readme file. It is not very obvious that the crawler won't fetch images or pdfs basically binary content by default unless we set the config to **includeBinaryContentInCrawling**. 
Though there is an example for image crawling explicitly, but to me it is not obvious that this example config is generic to include any binary content not just image. I had to debug the code for a while to understand about this setting.
Hence, I feel this setting should be a part of the [Configuration Details](https://github.com/yasserg/crawler4j#configuration-details) section on the readme page.

Please let me know what do you think. If you agree on the same, I would like to raise a PR for this change.

Regards,
Harshita Kasera

**Comment by s17t** [comment]
Hello, please just raise the PR, thank you!

**Comment by Chaiavi** [comment]
Thanks Harshita,

That would be very good to have.

**Comment by hkasera** [comment]
That is great! Thank you! I will start working on it and send a PR in a couple of days.
