### ISSUE TITLE
Resume crawling is not working, gives Sleepycat lock expired

### ISSUE THREAD

**Issue by progrock2002** [yasserg/crawler4j#257]
When enabling resume in configuration I get the following error:
2017-10-30 10:10:59,860 ERROR   Thread-9        Frontier        Frontier.java:80        Error while initializing the Frontier
com.sleepycat.je.LockTimeoutException: (JE 5.0.84) Lock expired. Locker 1080140418 1370_Thread-9_Txn: waited for lock on database=InProcessPagesDB LockAddr:5875855 LSN=0x0/0x9a68 type=WRITE grant=WAIT_PROMOTION timeoutMillis=500 startTime=1509354659359 endTime=1509354659859
Owners: [<LockInfo locker="1080140418 1370_Thread-9_Txn" type="READ"/>, <LockInfo locker="1055602406 724_JobThread-CrawlVwSites_Txn" type="READ"/>]
Waiters: []
Transaction 1080140418 1370_Thread-9_Txn owns LockAddr:5875855 <LockInfo locker="1080140418 1370_Thread-9_Txn" type="READ"/>
Transaction 1080140418 1370_Thread-9_Txn waits for LockAddr:5875855

        at com.sleepycat.je.txn.LockManager.newLockTimeoutException(LockManager.java:664) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.txn.LockManager.makeTimeoutMsgInternal(LockManager.java:623) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.txn.SyncedLockManager.makeTimeoutMsg(SyncedLockManager.java:97) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.txn.LockManager.lockInternal(LockManager.java:390) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.txn.LockManager.lock(LockManager.java:276) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.txn.Txn.lockInternal(Txn.java:510) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.txn.Locker.lock(Locker.java:443) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2636) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.dbi.CursorImpl.delete(CursorImpl.java:1353) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.Cursor.deleteNoNotify(Cursor.java:2095) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.Cursor.deleteInternal(Cursor.java:2059) ~[je-5.0.84.jar:5.0.84]
        at com.sleepycat.je.Cursor.delete(Cursor.java:696) ~[je-5.0.84.jar:5.0.84]
        at edu.uci.ics.crawler4j.frontier.WorkQueues.delete(WorkQueues.java:103) ~[crawler4j-4.3.jar:?]
        at edu.uci.ics.crawler4j.frontier.Frontier.<init>(Frontier.java:71) [crawler4j-4.3.jar:?]
        at edu.uci.ics.crawler4j.crawler.CrawlController.<init>(CrawlController.java:123) [crawler4j-4.3.jar:?]
        at de.volkswagen.foss.crawl.CrawlVwSites$VwSiteCrawlController.<init>(CrawlVwSites.java:96) [de.volkswagen.foss-0.0.1-SNAPSHOT.jar:?]
        at de.volkswagen.foss.crawl.CrawlVwSites.startNextCrawler(CrawlVwSites.java:286) [de.volkswagen.foss-0.0.1-SNAPSHOT.jar:?]
        at de.volkswagen.foss.crawl.CrawlVwSites$VwSiteCrawlController.startNextCrawler(CrawlVwSites.java:102) [de.volkswagen.foss-0.0.1-SNAPSHOT.jar:?]
        at de.volkswagen.foss.crawl.VwSiteCrawler.onBeforeExit(VwSiteCrawler.java:141) [de.volkswagen.foss-0.0.1-SNAPSHOT.jar:?]
        at edu.uci.ics.crawler4j.crawler.CrawlController$1.run(CrawlController.java:309) [crawler4j-4.3.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

Is there an option to increase the lock timeout?

**Comment by shalipoto** [comment]
I'm not familiar with that section of the codebase but I'll look into it ASAP. Sorry that you're not getting too much attention the issue.

**Comment by shalipoto** [comment]
> Transaction 1080140418 1370_Thread-9_Txn owns LockAddr:5875855 
Transaction 1080140418 1370_Thread-9_Txn waits for LockAddr:5875855

You might have a deadlock. I just noticed that the the owner of the lock is waiting on the same lock.

**Comment by shalipoto** [comment]
can you send me the project jar file or better yet, the crawler4j's pom.xml file? You might be using an older version of the sleepycat DB that has some have mentioned deadlock issues back in 2015.

**Comment by progrock2002** [comment]
Hi,

 

please find below the pom.xml (the defined version 5.0.84 of sleepycat is actually used, there is no version clash):

 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

       <modelVersion>4.0.0</modelVersion>

       <groupId>edu.uci.ics</groupId>

       <artifactId>crawler4j</artifactId>

       <packaging>jar</packaging>

       <name>crawler4j</name>

       <version>4.3</version>

       <description>Open Source Web Crawler for Java</description>

       <url>https://github.com/yasserg/crawler4j</url>

 

       <licenses>

             <license>

                    <name>The Apache Software License, Version 2.0</name>

                    <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>

                    <distribution>repo</distribution>

             </license>

       </licenses>

       <scm>

             <url>https://github.com/yasserg/crawler4j</url>

             <connection>scm:git:git@github.com:yasserg/crawler4j.git</connection>

              <developerConnection>scm:git:git@github.com:yasserg/crawler4j.git</developerConnection>

         <tag>crawler4j-4.3</tag>

  </scm>

       <distributionManagement>

             <snapshotRepository>

                    <id>ossrh</id>

                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>

             </snapshotRepository>

             <repository>

                    <id>ossrh</id>

                    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>

             </repository>

       </distributionManagement> 

 

       <properties>

             <slf4j.version>1.7.22</slf4j.version>

             <logback.version>1.1.7</logback.version>

             <guava.version>21.0</guava.version>

             <apache.http.components.version>4.5.3</apache.http.components.version>

             <je.version>5.0.84</je.version>

             <apache.tika.version>1.14</apache.tika.version>

             

             <junit.version>4.12</junit.version>

             <wiremock.version>2.4.1</wiremock.version>

             <spock.version>1.0-groovy-2.4</spock.version>

             <groovy.version>2.4.7</groovy.version>

       </properties>

 

       <parent>

             <groupId>org.sonatype.oss</groupId>

             <artifactId>oss-parent</artifactId>

             <version>7</version>

       </parent>

 

       <profiles>

             <profile>

                    <id>release</id>

 

                    <build>

                           <plugins>

                                  

                                  <plugin>

                                        <groupId>org.apache.maven.plugins</groupId>

                                        <artifactId>maven-source-plugin</artifactId>

                                        <version>2.4</version>

                                        <executions>

                                               <execution>

                                                      <id>attach-sources</id>

                                                      <goals>

                                                             <goal>jar</goal>

                                                      </goals>

                                               </execution>

                                        </executions>

                                  </plugin>

                                  

                                  <plugin>

                                        <groupId>org.apache.maven.plugins</groupId>

                                        <artifactId>maven-javadoc-plugin</artifactId>

                                        <version>2.10.1</version>

                                        <configuration>

                                               <additionalparam>-Xdoclint:none</additionalparam>

                                        </configuration>

                                        <executions>

                                               <execution>

                                                      <id>attach-javadocs</id>

                                                      <goals>

                                                             <goal>jar</goal>

                                                      </goals>

                                               </execution>

                                        </executions>

                                  </plugin>

                                  <plugin>

                                        <groupId>org.apache.maven.plugins</groupId>

                                        <artifactId>maven-gpg-plugin</artifactId>

                                        <version>1.5</version>

                                        <executions>

                                               <execution>

                                                      <id>sign-artifacts</id>

                                                      <phase>verify</phase>

                                                      <goals>

                                                             <goal>sign</goal>

                                                      </goals>

                                               </execution>

                                        </executions>

                                  </plugin>

                                  <plugin>

                                        <groupId>org.sonatype.plugins</groupId>

                                        <artifactId>nexus-staging-maven-plugin</artifactId>

                                        <version>1.6.7</version>

                                        <extensions>true</extensions>

                                        <configuration>

                                               <serverId>ossrh</serverId>

                                               <nexusUrl>https://oss.sonatype.org/</nexusUrl>

                                               <autoReleaseAfterClose>true</autoReleaseAfterClose>

                                        </configuration>

                                  </plugin>

                                  <plugin>

                                        <groupId>org.apache.maven.plugins</groupId>

                                        <artifactId>maven-release-plugin</artifactId>

                                        <version>2.5.3</version>

                                        <configuration>

                                               <autoVersionSubmodules>true</autoVersionSubmodules>

                                               <useReleaseProfile>false</useReleaseProfile>

                                               <releaseProfiles>release</releaseProfiles>

                                               <goals>deploy</goals>

                                        </configuration>

                                  </plugin>

                           </plugins>

                    </build>

             </profile>

 

             <profile>

                    <id>fatjar</id>

                    <build>

                           <plugins>

                                  <plugin>

                                        <artifactId>maven-assembly-plugin</artifactId>

                                        <version>2.5.3</version>

                                        <configuration>

                                               <descriptorRefs>

                                                      <descriptorRef>jar-with-dependencies</descriptorRef>

                                               </descriptorRefs>

                                        </configuration>

                                        <executions>

                                               <execution>

                                                      <id>make-fat-jar</id>

                                                      <phase>package</phase>

                                                      <goals>

                                                             <goal>single</goal>

                                                      </goals>

                                                      <configuration>

                                                             <finalName>crawler4j-${project.version}</finalName>

                                                      </configuration>

                                               </execution>

                                        </executions>

                                  </plugin>

                           </plugins>

                    </build>

             </profile>

       </profiles>

 

       <build>

             <plugins>

                    <plugin>

                           <groupId>org.apache.maven.plugins</groupId>

                           <artifactId>maven-compiler-plugin</artifactId>

                           <version>3.2</version>

                           <configuration>

                                  <source>1.8</source>

                                  <target>1.8</target>

                           </configuration>

                    </plugin>

                    <plugin>

                           <groupId>org.apache.maven.plugins</groupId>

                           <artifactId>maven-jar-plugin</artifactId>

                           <version>2.5</version>

                           <configuration>

                                  <excludes>

                                        <exclude>**/*.properties</exclude>

                                  </excludes>

                           </configuration>

                    </plugin>

                    <plugin>

                           <groupId>org.apache.maven.plugins</groupId>

                           <artifactId>maven-checkstyle-plugin</artifactId>

                           <version>2.17</version>

                           <executions>

                                  <execution>

                                        <id>compile</id>

                                        <phase>compile</phase>

                                        <configuration>

                                               <configLocation>checkstyle.xml</configLocation>

                                               <encoding>UTF-8</encoding>

                                               <consoleOutput>true</consoleOutput>

                                               <failsOnError>true</failsOnError>

                                               <includeTestSourceDirectory>true</includeTestSourceDirectory>

                                        </configuration>

                                        <goals>

                                               <goal>check</goal>

                                        </goals>

                                  </execution>

                           </executions>

                           <dependencies>

                                  <dependency>

                                        <groupId>com.puppycrawl.tools</groupId>

                                        <artifactId>checkstyle</artifactId>

                                        <version>7.1</version>

                                  </dependency>

                           </dependencies>

                    </plugin>

            <plugin>

                <groupId>org.jacoco</groupId>

                <artifactId>jacoco-maven-plugin</artifactId>

                <version>0.7.9</version>

                <executions>

                    <execution>

                        <id>pre-unit-test</id>

                        <goals>

                            <goal>prepare-agent</goal>

                        </goals>

                    </execution>

                    <execution>

                        <id>post-unit-test</id>

                        <phase>test</phase>

                        <goals>

                            <goal>report</goal>

                        </goals>

                        <configuration>

                            <excludes>

                                <exclude>**/exceptions/**</exclude>

                            </excludes>

                        </configuration>

                    </execution>

                </executions>

            </plugin>

                    

                    <plugin>

                           <groupId>org.codehaus.gmavenplus</groupId>

                           <artifactId>gmavenplus-plugin</artifactId>

                           <version>1.5</version>

                           <executions>

                                  <execution>

                                        <goals>

                                               <goal>addSources</goal>

                                               <goal>addTestSources</goal>

                                               <goal>generateStubs</goal>

                                               <goal>compile</goal>

                                               <goal>testGenerateStubs</goal>

                                               <goal>testCompile</goal>

                                               <goal>removeStubs</goal>

                                               <goal>removeTestStubs</goal>

                                        </goals>

                                  </execution>

                           </executions>

                    </plugin>

                    <plugin>

                           <groupId>org.codehaus.mojo</groupId>

                           <artifactId>build-helper-maven-plugin</artifactId>

                           <version>1.9.1</version>

                           <executions>

                                  <execution>

                                        <id>add-source</id>

                                        <phase>generate-sources</phase>

                                        <goals>

                                               <goal>add-source</goal>

                                        </goals>

                                        <configuration>

                                               <sources>

                                                      <source>src/main/groovy</source>

                                               </sources>

                                        </configuration>

                                  </execution>

                                  <execution>

                                        <id>add-test-source</id>

                                        <phase>generate-test-sources</phase>

                                        <goals>

                                               <goal>add-test-source</goal>

                                        </goals>

                                        <configuration>

                                               <sources>

                                                      <source>src/test/groovy</source>

                                               </sources>

                                        </configuration>

                                  </execution>

                           </executions>

                    </plugin>

             </plugins>

       </build>

 

       <dependencies>

 

    

 

    <dependency>

        

        <groupId>org.slf4j</groupId>

        <artifactId>slf4j-api</artifactId>

        <version>${slf4j.version}</version>

    </dependency>

    <dependency>

        

        <groupId>ch.qos.logback</groupId>

        <artifactId>logback-classic</artifactId>

        <version>${logback.version}</version>

        <scope>runtime</scope>

    </dependency>

    <dependency>

        

        <groupId>com.google.guava</groupId>

        <artifactId>guava</artifactId>

        <version>${guava.version}</version>

    </dependency>

       <dependency>

             <groupId>org.apache.httpcomponents</groupId>

             <artifactId>httpclient</artifactId>

             <version>${apache.http.components.version}</version>

             <scope>compile</scope>

       </dependency>

 

       <dependency>

             <groupId>com.sleepycat</groupId>

             <artifactId>je</artifactId>

             <version>${je.version}</version>

       </dependency>

 

       <dependency>

             <groupId>org.apache.tika</groupId>

             <artifactId>tika-parsers</artifactId>

             <version>${apache.tika.version}</version>

       </dependency>

 

    

             <dependency>

                    <groupId>junit</groupId>

                    <artifactId>junit</artifactId>

                    <version>${junit.version}</version>

                    <scope>test</scope>

             </dependency>

             <dependency>

                    <groupId>com.github.tomakehurst</groupId>

                    <artifactId>wiremock</artifactId>

                    <version>${wiremock.version}</version>

                    <scope>test</scope>

             </dependency>

             <dependency>

                    <groupId>org.codehaus.groovy</groupId>

                    <artifactId>groovy-all</artifactId>

                    <version>${groovy.version}</version>

                    <scope>test</scope>

             </dependency>

             <dependency>

                    <groupId>org.spockframework</groupId>

                    <artifactId>spock-core</artifactId>

                    <version>${spock.version}</version>

                    <scope>test</scope>

             </dependency>

       </dependencies>

 

       <repositories>

             <repository>

                    <id>oracleReleases</id>

                    <name>Oracle Released Java Packages</name>

                    <url>http://download.oracle.com/maven</url>

                    <layout>default</layout>

             </repository>

       </repositories>

 

</project>

 

 

Von: shalipoto [mailto:notifications@github.com] 
Gesendet: Mittwoch, 1. November 2017 01:07
An: yasserg/crawler4j <crawler4j@noreply.github.com>
Cc: progrock2002 <stefan@zs-net.de>; Author <author@noreply.github.com>
Betreff: Re: [yasserg/crawler4j] Resume crawling is not working, gives Sleepycat lock expired (#257)

 

can you send me the project jar file or better yet, the crawler4j's pom.xml file? You might be using an older version of the sleepycat DB that has some have mentioned deadlock issues back in 2015.

**Comment by shalipoto** [comment]
The sleeycat je version looks ok. There is a way to change the lock timeout if you would like to do that.
Navigate to the CrawlController.java file and search for the line with `envConfig.setLocking(resumable)`

Then add these lines of code just after that:
```
 envConfig.setLockTimeout(3000L, TimeUnit.MILLISECONDS);
 logger.debug("The DB lock timeout has been set to 3000ms");

```
This is setting the timeout now to 3 seconds.

**Comment by s17t** [comment]
It is possible to set that Sleepycat property with CrawlConfig's DbLockTimeout.
