### ISSUE TITLE
JavaScript inside htmlParseData.getText()

### ISSUE THREAD

**Issue by loxal** [yasserg/crawler4j#259]
Indexing `https://www.migrosbank.ch/it/aziende/investire/interesse-deposito.html` gives me `htmlParseData.getText()` with JavaScript inside. The URL above is just one of many examples where JavaScript is not stripped.

**Comment by shalipoto** [comment]
I looked at the parser and added  the htmlParser.setExtractScripts(false) and it did exclude some scripts but not others from the page at url https://www.migrosbank.ch/de/privatpersonen.html

I'm not sure why tagsoup is doing this but it may be a bug.

**Comment by shalipoto** [comment]
It looks like using a new tag mapper class holding a list of tags to ignore (SCRIPT, STYLE) [at my crawler fork](https://github.com/shalipoto/crawler4j/tree/html-js-ignore) works for me on the url seed you provided above.

**Comment by shalipoto** [comment]
@loxal , I'll continue looking at this issue next.

**Comment by s17t** [comment]
@loxal, users should extract text from page with their own means in `visit` method using their specific parser (i.e. using a new tika with custom configuration, using jsoup).

The parsedData is used just to extract all text that could contains links to crawler thus, `<script>` tag included. It is available to user for convenience but I think the lib should just expose the whole HTML page text.

In your crawler `visit` method:
```    @Override
    public void visit(Page page) {
      // Use tika with your config here or JSoup.
    }
```
