### ISSUE TITLE
CrawlConfig.toString() might leak sensitive information

### ISSUE THREAD

**Issue by rcaa** [yasserg/crawler4j#260]
I noticed that CrawlConfig.toString() includes proxy password. In case someone might carelessly call toString method, she might leak sensitive information. 

Should I submit a pull request fixing this issue?

**Comment by shalipoto** [comment]
Please do. Also you can do the same at [my fork](https://github.com/shalipoto/crawler4j)  as well please?

**Comment by rcaa** [comment]
Done.

**Comment by shalipoto** [comment]
Thank you.

**Comment by s17t** [comment]
Fixed in #265
