### ISSUE TITLE
HTML escape sequences like &ouml; are extracted with an extra space character

### ISSUE THREAD

**Issue by loxal** [yasserg/crawler4j#261]
In 

view-source:https://www.extendshop.de/index/extend-orange/news-und-events/internetschutz.html

...you can find...

`Zugangsdaten, Passw&ouml;rtern und Kreditkarten online`

...and instead of...

> Zugangsdaten, Passwörtern und Kreditkarten online

...I get...

> Zugangsdaten, Passw örtern und Kreditkarten online

(with a space character, near **ö**)

**Comment by shalipoto** [comment]
@loxal , below is what I now can get parsing your url given above. It's not pretty but the parser is handling HTML escape sequences alright so far in testing. I'm not addressing scripts at the moment.

Nach oben 
     
 


     
         Menü 
       
                       Zum Girokonto 

               
                       Leistungen 

               
                       Mein extend 

               
                       BW extend orange 

       
                       Übersicht 

               
                                                     News und Events 
 

               
                       Dauerangebote 

               
               
     



 
             
         
             
             
         
         
         
            IFS.jQuery.noConflict();
            IFS.jQuery(document).ready(function ($) {
                IFS.initClient({
                    customConfig: {
                        overwrite: {
                            "appLang": "de"
                        }
                    },
                    sbTarget: "#searchbar",
                    configurl: "https://api.s itesearch.cloud/searchbar-config/sitesearch-config.json",
                    sitesearch: true,
                    siteId: "269b0538-120b-44b1-a365-488c2f3fcc15"
                });
            });
         
 

 
     
         Anmelden 
 
 




 
     
        


 
         
         « zurück zu extend orange News und Events 
 

         





 
        
         
         
        
         
         Online? Aber sicher! 
         Der SV InternetSchutz bietet Hilfe bei Online-Betrug und Datendiebstahl. 
    
         Sich vor Online-Betrügern sicher zu fühlen ist eine Sache – tatsächlich sicher zu sein eine andere. Um die digitalen Schäfchen auch wirklich ins Trockene zu bringen, gibt’s den InternetSchutz der BW-Bank. 

 Das mit der Internetsicherheit ist so eine Sache: Im Grunde meint jeder zu wissen, was er online tun und lassen kann. Gerade wer als „digital native“ die Internetaffinität schon im Grundschulalter entwickelt hat, lässt sich ungern von der älteren Generation erklären, dass in der nachmittäglichen Ratgeber-Sendung vor Cyberkriminalität gewarnt wurde. Schließlich reicht oft schon  grundlegende Medienkompetenz, um das digitale Hab und Gut zu schützen. 

 Sämtliche Transaktionen und Geschäfte online abwickeln zu können, ist herrlich bequem, schnell und einfach. Doch wo Geld im Spiel ist, bleiben Kriminelle nicht fern und so ergeben sich Online-Banking sowie Onlineshopping-Plattformen als natürliches Ziel für Betrug. Eine umfassende Internetschutz-Versicherung mindert solche Sorgen. Sollte es nämlich tatsächlich zum Betrugsfall k ommen, sind Sie mit dem SV InternetSchutz als Nutzer gegen sämtliche Vermögensschäden aus Online-Geschäften geschützt. 

 Der informierte Internetnutzer weiß, dass sich gerade in sozialen Medien viele gefälschte Profile tummeln – meist erkennt man sie auf den ersten Blick und quittiert sie lediglich mit einem Augenrollen. Weniger schön ist es allerdings, wenn man unter den Profilbildern solcher Accounts plötzlich sein eigenes entdeckt. Oder wenn Betrüger mit sämtlichen Zugangsdaten, Passwörtern un d Kreditkarten online großen Schaden anrichten. Auch in solchen Fällen des Identitätsmissbrauchs hilft der SV InternetSchutz dabei, Schäden durch Phishing, Pharming und Skimming zu versichern. 

 War eine Online-Attacke trotz aller Vorsichtsmaßnahmen erstmal erfolgreich, dann gilt die oberste Priorität der Datensicherung. Denn trotz zahlloser Empfehlungen am besten täglich Back-ups der persönlichen Daten zu erstellen, tun dies noch immer die Wenigsten. Um in einer Krisensituation zu verhindern, dass sämtliche Daten mit einem Mal verschwunden sind, steht der InternetSchu tz Notfallservice 365 Tage im Jahr rund um die Uhr zur Verfügung und vermittelt so schnell wie möglich weiter an eine Fachfirma, die auf Datenrettung spezialisiert ist. 

 Eins ist jedenfalls klar: Internetsicherheit ist unheimlich wichtig und sollte trotz aller Kenntnis des Mediums nicht auf die leichte Schulter genommen werden. Gerade in Zeiten der rasanten Entwicklung von Online-Nutzungsmöglichkeiten ist es wichtiger als je zuvor, auch hier immer auf dem neuesten Stand zu bleiben. Mit dem umfassenden InternetSchutz unseres Partners SV Sparkass enVersicherung sind Sie auf der sicheren Seite und können so ganz entspannt die zahlreichen Vorteile der Online-Welt nutzen.                                                                            

 Kurz und knapp – hier gibt’s die InternetSchutz Vorteile auf einen Blick: 

 Schutz vor Vermögensschäden bei Online-Transaktionen und Onlineshopping Schutz vor Vermögensschäden nach Identitätsmissbrauch 24/7 Notfallunterstützung (z. B. Kartensperrung) Rettung persönlicher Daten Versicherung von Schäden durch Phishing, Pharming und Skimming Löschung von rufschädigenden Inhalten im Netz Juristische Erstberatung Psychologische Erstberatung Persönliche Ansprechpartner nur 49 € im Jahr für den ganzen Familienhaushalt 

 Einfach jetzt online über  >> www.bw-bank.de/internetschutz  abschließen oder in der Filiale bzw. bei der Videoberatung über weitere Absicherungsbausteine informieren. 

   

         
 
         
 
    
     
                 Bausparvertrag 
             «  Voriger Beitrag 
     

     
                 ISIC 
             Nächster Beitrag  » 
     
 
     


     
        $(document).ready(function () {
           calculateTeaserInRow();
        });
     

 

 
    






        

     
             
         
             
                AssetGo
             
         

         
                     Laden Sie jetzt kostenlos die neue Investment-App der BW-Bank auf Ihr Smartphone. Marktdaten,  exklusive Analysen, mobiles Trading und vieles mehr.  
             Mehr erfahren » 
         
     








        

     
             
         
             
                Eine App für alle(s):
             
         

         
                     Bankübergreifende Kontrolle  über Ihre Finanzen - BW Mobilbanking  unterstützt nun auch Konten anderer  deutscher Banken und Sparkassen.   
             Mehr erfahren » 
         
     


 

     
    	 Inhalt im Web teilen: 
    	 
     


 
     Sie sind hier: 
     Startseite BW extend orange News und Events InternetSchutz 
 



 
     
        
 
             Unternehmen 

 
             Zur BW-Bank » 
     
             Zum Onlinebanking » 
     
             Zum Filialfinder » 
     
 

 
             Rechtliches 

 
             Impressum » 
     
             Rechtliche Hinweise » 
     
             Datenschutz » 
     
 

 
         Haben Sie noch Fragen? 
    
     Service Hotline 

 0711 124-37000 

 Mo-Sa: 8:00 - 22:00 Uhr, 
So: 10:00 - 18:00 Uhr 

 Notfall Hotline 

 0711 124-44533 

 Kontaktformular » 

 
     
 

 
    	

 
BW extend im Überblick
 

 


 
             Zum Girokonto 

 
             X Möglichkeiten » 
     
             Tarif-Finder » 
     
             Tarifvergleich » 
     
             BW extend gold » 
     
             BW extend classic » 
     
             BW extend orange » 
     
 

 
             Angebote 

 
             Übersicht » 
     
             Aktionsangebote » 
     
             Freizeit-Möglichkeiten » 
     
             Reise-Möglichkeiten » 
     
             Bank-Möglichkeiten » 
     
             BW extend orange » 
     
             Veranstaltungskalender » 
     
 

 
             Aktuelles 

 
             Übersicht » 
     
             extend News » 
     
             extend orange News & Events » 
     
             Veranstaltungskalender » 
     
             Ticket-Shop » 
     
             Reise-Shop » 
     
 

 
             Mein extend 

 
             Übersicht » 
     
             Meine Daten » 
     
             Sicherheitsportal » 
     
             Hotlines » 
     
             Virtuelle Kundenkarte » 
     
             Newsletter » 
     
 
 

             
                 extend Vorteil 
             
     


         
             extend Adventskalender - täglich attraktive Preise gewinnen 
                 Tickets, Reisegutscheine und vieles mehr. Jetzt Türchen öffnen und täglich tolle Preise im Gesamtwert von über 4.000 € gewinnen. 


                 Zum Adventskalender 
         

         
                #newsletter-message {
                    background: rgba(0, 0, 0, 0) url("/dam/jcr:c82f57d8-ad2f-4521-b933-5d2b7032fbf1/connectors-20171121103317822%20(3).2017-12-11-09-40-30.jpg") no-repeat scroll right bottom;
                }


            .sticky-wrapper {
                display: block;
            }
         

             
                $(document).ready(function() {
                    $.ajax({
                        url: '/index/newsletter/singleton.html',
                        type: 'POST',
                        dataType: 'json',
                        success: function(ajaxData, status, xhr) {
                            if (ajaxData.openLayer) {
                                $.fan cybox.open('#newsletter-message');
                            }
                        },
                        error: function(error, status, xhr) {
                            console.log(error, status, xhr);
                        }
                    });
                });

**Comment by loxal** [comment]
I did not expect that you do not address *script removal* which would be a deal breaker for many use cases that want a content extraction crawler.

**Comment by shalipoto** [comment]
Sorry for the letdown, the fix here for #261 was not trivial as I had to correct logic errors in the tagsoup parser which is a crawler4j dependency.

**Comment by shalipoto** [comment]
@loxal , can you do me a favor please?

**Comment by s17t** [comment]
@shalipoto would you pull request the fix ? Thank you !
