### ISSUE TITLE
Is it possible to feed only the pages we want?

### ISSUE THREAD

**Issue by NunoPontes** [yasserg/crawler4j#264]
Hello,

I'd like to know if it's possible to feed the crawler a list of websites, and the crawler only visits those and only those using multiple crawlers?

**Comment by Chaiavi** [comment]
Yes.

Just set the depth of the crawling to 0 I think

**Comment by NunoPontes** [comment]
That would require the addSeed() to accept a list of Strings url's for example, and yet it only accepts a single string. In my example I have more than 40000 url's that I'd like to access, it's not ok to do addseed a every single one

**Comment by shalipoto** [comment]
A zero crawl depth should work .Then you would have to add logic to read in your url list and addSeed() each one.

**Comment by ChristianLJ** [comment]
@NunoPontes can't you do the following?
`for(String url : urls) {
    controller.addSeed(url);
}`

**Comment by NunoPontes** [comment]
Yes, that's what I've done, but I can't check it out right now if the performance improved. Today, I'll let you know if the performance is the same if I only use 1 thread on this

**Comment by NunoPontes** [comment]
It's working. Thank you
