### ISSUE TITLE
How we can delay per second subsequent calls to same website to avoid DoS attack?

### ISSUE THREAD

**Issue by pw6591** [yasserg/crawler4j#268]

**Comment by shalipoto** [comment]
Did you set the politeness delay [here](https://github.com/yasserg/crawler4j/blob/master/crawler4j/src/test/java/edu/uci/ics/crawler4j/examples/basic/BasicCrawlController.java)?

` /*
     * Be polite: Make sure that we don't send more than 1 request per
     * second (1000 milliseconds between requests).
     */
        config.setPolitenessDelay(1000);`

Its already set at 1000 which means 1 second. I hope this answers your question.

**Comment by shalipoto** [comment]
Please let us know if this helped and closing the issue, as we would like to continue helping as time permits!

**Comment by pw6591** [comment]
Thanks for the solutions

**Comment by shalipoto** [comment]
Alright, no problem
