### ISSUE TITLE
Memory leak? (very long Finalizers)

### ISSUE THREAD

**Issue by hayarobi** [yasserg/crawler4j#273]
I have hard time with crawler4j now. It seems that there is trouble to GC objects... 

Here is snapshot in MAT
<img width="2577" alt="crawler4j_finalizer" src="https://user-images.githubusercontent.com/3103946/34200801-c6e1be0a-e5b5-11e7-9d6f-6613f01394c8.png">
the Finalizers are more that 100... the mat limits to show this chain up to 100.

The attribute "referent" of that Finalizer objects is like below:

java.util.concurrent.ThreadPoolExecutor
edu.uci.ics.crawler4j.fetcher.SniPoolingHttpClientConnectionManager
java.io.FileOutputStream
java.util.concurrent.ThreadPoolExecutor
sun.security.ssl.SSLSessionImpl
sun.security.ssl.SSLSessionImpl
edu.uci.ics.crawler4j.fetcher.SniPoolingHttpClientConnectionManager
java.io.FileOutputStream
java.util.concurrent.ThreadPoolExecutor
java.net.SocksSocketImpl
...

My app crawl just first page and css and js file that the first pages loaded. And about 10 threads are crawling concurrently, totally 1000 pages per hour. It works fine at first, but it fails to crawl some hours after. 

It's snippet of my code.

`package io.blocko.kisti.forgemonitor.app.detector;

import java.io.File;
import java.net.URLDecoder;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import edu.uci.ics.crawler4j.crawler.CrawlConfig;
import edu.uci.ics.crawler4j.crawler.CrawlController;
import edu.uci.ics.crawler4j.crawler.CrawlController.WebCrawlerFactory;
import edu.uci.ics.crawler4j.crawler.Page;
import edu.uci.ics.crawler4j.fetcher.PageFetcher;
import edu.uci.ics.crawler4j.robotstxt.RobotstxtConfig;
import edu.uci.ics.crawler4j.robotstxt.RobotstxtServer;
import com.github.hayarobi.crawler.misc.HashUtil;
import com.github.hayarobi.crawler.vo.PageSource;

public class Crawler4JImplCopy implements WebCrawlerFactory<SingleDepthCrawler>, SourceCrawlListener {
	private static final String UNKNOWN_MIMETYPE = "application/octet-stream";
	private static final String HEADER_STRING_USERAGENT = "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36";
	private final static Charset UTF8 = Charset.forName("UTF-8");

	static Logger log = LoggerFactory.getLogger(Crawler4JImplCopy.class);

	private final String url;

	private final String crawlStorageFolder;

	private CrawlConfig crawlConfig;

	private ConcurrentLinkedQueue<PageSource> crawledSources;
	
	public Crawler4JImplCopy(String url, String crawlStorageFolder) {
		super();
		this.url = url;
		this.crawlStorageFolder = crawlStorageFolder+File.separator+encode(url);
	}

	protected void init() {
		crawlConfig = new CrawlConfig();
		crawlConfig.setCrawlStorageFolder(crawlStorageFolder);
		crawlConfig.setIncludeBinaryContentInCrawling(true);
		crawlConfig.setPolitenessDelay(250);
		crawlConfig.setMaxDepthOfCrawling(1);
		crawlConfig.setUserAgentString(HEADER_STRING_USERAGENT);
		crawlConfig.setThreadShutdownDelaySeconds(5);
		crawlConfig.setThreadShutdownDelaySeconds(3);
		crawlConfig.setCleanupDelaySeconds(3);
	}

	public List<PageSource> crawlPage() throws CrawlingFailedException {
		crawledSources = new ConcurrentLinkedQueue<>();

        PageFetcher pageFetcher = new PageFetcher(crawlConfig);
        RobotstxtConfig robotstxtConfig = new RobotstxtConfig();
        robotstxtConfig.setEnabled(false);
        RobotstxtServer robotstxtServer = new RobotstxtServer(robotstxtConfig, pageFetcher);
        CrawlController controller;
		try {
			controller = new CrawlController(crawlConfig, pageFetcher, robotstxtServer);
		} catch (Exception e) {
			log.warn("Failed to create CrawlController.",e);
			throw new CrawlingFailedException("Failed to crawl url "+url+" : "+e.getMessage());
		}

        /*
         * For each crawl, you need to add some seed urls. These are the first
         * URLs that are fetched and then the crawler starts following links
         * which are found in these pages
         */
        controller.addSeed(url);
        
        /*
         * Start the crawl. This is a blocking operation, meaning that your code
         * will reach the line after this only when crawling is finished.
         */
        controller.start(this, 1);
        log.debug("Crawling finished");
        controller.waitUntilFinish();

        if( crawledSources.isEmpty() ) {
			throw new CrawlingFailedException("Failed to crawl url "+url+" : server responded not found, forbidden, or redirected");
        }
        return new ArrayList<>(crawledSources);
	}

	public static String urlDecode(String s) {
		boolean needToChange = false;
		int numChars = s.length();
		StringBuilder sb = new StringBuilder(numChars > 500 ? numChars / 2 : numChars);
		int i = 0;

		char c;
		byte[] bytes = null;
		while (i < numChars) {
			c = s.charAt(i);
			switch (c) {
			case '+':
				sb.append(' ');
				i++;
				needToChange = true;
				break;
			case '%':
				/*
				 * Starting with this instance of %, process all consecutive
				 * substrings of the form %xy. Each substring %xy will yield a
				 * byte. Convert all consecutive bytes obtained this way to
				 * whatever character(s) they represent in the provided
				 * encoding.
				 */

				try {

					// (numChars-i)/3 is an upper bound for the number
					// of remaining bytes
					if (bytes == null)
						bytes = new byte[(numChars - i) / 3];
					int pos = 0;

					while (((i + 2) < numChars) && (c == '%')) {
						int v = Integer.parseInt(s.substring(i + 1, i + 3), 16);
						if (v < 0)
							throw new IllegalArgumentException(
									"URLDecoder: Illegal hex characters in escape (%) pattern - negative value");
						bytes[pos++] = (byte) v;
						i += 3;
						if (i < numChars)
							c = s.charAt(i);
					}

					// A trailing, incomplete byte encoding such as
					// "%x" will cause an exception to be thrown

					if ((i < numChars) && (c == '%'))
						throw new IllegalArgumentException("URLDecoder: Incomplete trailing escape (%) pattern");

					sb.append(new String(bytes, 0, pos, UTF8));
				} catch (NumberFormatException e) {
					throw new IllegalArgumentException(
							"URLDecoder: Illegal hex characters in escape (%) pattern - " + e.getMessage());
				}
				needToChange = true;
				break;
			default:
				sb.append(c);
				i++;
				break;
			}
		}

		return (needToChange ? sb.toString() : s);
	}

	private String encode(String url2) {
		return url2;
	}

	public static String extractFilenameFrom(String url) {
		int offset = url.lastIndexOf("/");
		if( offset >= url.length()-1 ) {
			return "";
		} else {
			return url.substring(offset+1);			
		}
	}
	
	@Override
	public SingleDepthCrawler newInstance() throws Exception {
		return new SingleDepthCrawler(url, this);
	}
	
	public void onCrawlSource(Page page, byte[] data) {
		PageSource pageSource = new PageSource();
		pageSource.setContextPath(page.getWebURL().getPath());
		pageSource.setFileName(extractFilenameFrom(page.getWebURL().getURL()));
		pageSource.setMimeType(extractMimeType(page.getContentType()));
		pageSource.setSize(data.length);
		pageSource.setData(data);
		pageSource.setChecksum(HashUtil.getHexstringSha256(data));
		
		crawledSources.add(pageSource);
		log.debug("Page {} was added to list", pageSource);
	}

	private static String extractMimeType(String contentType) {
		String[] splitted = contentType.split(";");
		if( splitted.length < 1) {
			return UNKNOWN_MIMETYPE;
		}
		return splitted[0].trim();
	}
}`

**Comment by s17t** [comment]
Hi @hayarobi, thank for the report. Would you be so kind to share a reproducible (and buildable) test case ? Thank you !

**Comment by hayarobi** [comment]
Unfortunately, I don't have enough time to make test code now, but I solved it by calling controller.shutdown() when crawling was finished.

I have to crawl same web page over and over again, and it's not the case described in Readme. So I create a new controller, start crawl, and discard that controller object periodically. The PageFetcher threads were not destroyed and that prevented GC. 

 It seems not a bug but a lack of documentation, unless the Controller was designed as auto-disposable. The links of More examples are broken now, it is sure issue now.

**Comment by s17t** [comment]
Thanks for your time. Yes, `shutdown()` method **must** be called. Indeed there is not much explicit documentation about this.
