### ISSUE TITLE
"config.setOnlineTldListUpdate(true)" doesn't work.

### ISSUE THREAD

**Issue by LSmyrnaios** [yasserg/crawler4j#282]
Hi,
I experimented a bit with CrawlController and found out that setting TLDList to update online doesn't work.
After looking inside the code, I noticed that `TLDList()` constructor is never called inside `CrawlController()` constructor, but still it somehow finds its way in my logger:

> INFO edu.uci.ics.crawler4j.url.TLDList - Obtained 6791 TLD from packaged file tld-names.txt

`CrawlController()` sets the user-defined value inline 96:
`TLDList.setUseOnline(config.isOnlineTldListUpdate());`
But it never actually initializes the TLDList... where does this initialization happen? And why `private static boolean onlineUpdate`

 remains false?

I tried to make it work by calling:
`TLDList.setUseOnline(true);`
`TLDList.getInstance();`
But it doesn't. Am I doing something wrong?

It's still odd the fact that it was supposed to work when we set the CrawlController to update TLDList online, but it just doesn't..
Also, why going though the `TLDList.getInstance();` to initialize it and not be able to call it directly:
`new TLDList();` ?

Please add a fix for this in 4.4.0.
Thanks

**Comment by s17t** [comment]
I confirm. The TLDList singleton is statically initialized, long before the configuration option is available. This is sad. I will try to fix.

**Comment by s17t** [comment]
de47bf8c497a619f86cea907de48500452d293d1 fix this.
