### ISSUE TITLE
Switch default branch to develop

### ISSUE THREAD

**Issue by s17t** [yasserg/crawler4j#286]
@yasserg could set the default branch to `develop`? There are number of features and PR (modules, alternative persistence) that would benefit from branch based development (sort of git-flow).

@rzo1 @Chaiavi would you agree ?

Fede

**Comment by yasserg** [comment]
Having multiple branches just makes it more complex to mange. Features like alternative persistence don't need a separate branch. They can be implemented by making the design more flexible.
