### ISSUE TITLE
WebCrawler.shouldFollowLinksIn should be called after visit

### ISSUE THREAD

**Issue by ThomasRitter75** [yasserg/crawler4j#293]
If link collection happens **after** a call to visit, the crawler can decide by content, if it should follow the links on that page. An important use case for this is the https://de.wikipedia.org/wiki/Canonical_Link so the crawler does not crawl duplicate content (exponential URL blowup by search parameters on shop categories for example). 
Suggestion: A very good way to do such things would be to pass the Page to shouldFollowLinksIn or add a custom data object to WebURL, so it can be marked while visiting (to prevent database overhead on crawlers).

**Comment by Chaiavi** [comment]
The *shouldVisit *method happens *before *url collection and before page
parsing.

If a page is parsed then the link aggregation takes almost no time and does
not impose almost any overhead - CPU or Memory alike.


URL Normalization is done on any URL so the same page won't be crawled more
than once.

**Comment by ThomasRitter75** [comment]
Version 4.4.0 solves this problem.
