### ISSUE TITLE
Cannot find crawler4j-4.3-with-dependencies.jar in release page

### ISSUE THREAD

**Issue by jackshang** [yasserg/crawler4j#298]
There has something wrong with crawler4j 4.3 denpends on crawler4j-4.1-with-dependencies.jar, it seems like incorrect version of httpcomponents-client in the crawler4j-4.1-with-dependencies.jar for crawler4j 4.3. 

But cannot find crawler4j-4.3-with-dependencies.jar in release page。Can you paste a link for it? thx.

Error:
#1 Class org.apache.http.conn.ssl.NoopHostnameVerifier can not be resolved;

**Comment by s17t** [comment]
> But cannot find crawler4j-4.3-with-dependencies.jar in release page

As clearly stated in README there is no official 4.3-with-dependencies distribution. If you need it you have to create it for yourself:

```
git clone git@github.com:yasserg/crawler4j.git
git checkout tags/crawler4j-4.3
mvn package -Pfatjar
ls -l target/crawler4j-4.3-jar-with-dependencies.jar
```

**Comment by jackshang** [comment]
The first time I browsed crawler4j, and read the crawler4j/wiki at first. You are right, I ignored the "Without Maven" part of README. Thanks for your great project.
