### ISSUE TITLE
spring integration

### ISSUE THREAD

**Issue by muska88** [yasserg/crawler4j#308]
Hi,
Do you have any idea to integrate the crawler with spring? Or do i have to check out the code and edit by myself(and also i wont be able to get your updates)?

**Comment by rzo1** [comment]
You can implement a `WebCrawlerFactory`, which is Spring-based and pass this implementation into the CrawlController.

**Comment by s17t** [comment]
This is documented in the README: 

https://github.com/yasserg/crawler4j#using-a-factory
