### ISSUE TITLE
"4.4.0-SNAPSHOT" in "pom.xml", after latest merge.

### ISSUE THREAD

**Issue by LSmyrnaios** [yasserg/crawler4j#309]
This is just a merge issue in the following commit, after the 4.4.0 version was released.
So it has either to be plain "4.4.0" or "4.5.0-SNAPSHOT" instead.
https://github.com/yasserg/crawler4j/commit/a5ccbe47230d3d6ca3286e433d87821f561ffd32

**Comment by s17t** [comment]
Thank you. It was unused property. Fixed in  6e59709
