### ISSUE TITLE
Endless behavior in a calendar url

### ISSUE THREAD

**Issue by yhdelgado** [yasserg/crawler4j#31]
I am trying to crawl PDF files from Open Journal System (OJS) Journal. However, after of several minutes, crawler4j has an endless behavior in a calendar url, such as:

http://rcci.uci.cu/index.php?journal=rcci&op=statistics&page=about&statisticsYear=7749

Note that the value of year at the end of URL change continuosly. Is there any way to change this behavior in crawler4j? My crawler configuration is as follow:

Resumable crawling: false
Max depth of crawl: -1
Max pages to fetch: -1
User agent string: crawler4j (http://code.google.com/p/crawler4j/)
Include https pages: true
Include binary content: true
Max connections per host: 100
Max total connections: 100
Socket timeout: 20000
Max total connections: 100
Max outgoing links to follow: 5000
Max download size: 5242880
Should follow redirects?: true
Proxy host: null
Proxy port: 80
Proxy username: null
Proxy password: null

Best regards.

**Comment by yasserg** [comment]
You can set the maximum depth of crawl to a small number (3 to 6).
