### ISSUE TITLE
SNAPSHOT builds are broken

### ISSUE THREAD

**Issue by s17t** [yasserg/crawler4j#310]
Snapshot build are broken [0]. @onebeartoe could you clean that jenkins workspace ? 

[0] https://onebeartoe.ci.cloudbees.com/job/crawler4j/

**Comment by onebeartoe** [comment]
I tried clearing the workspace, but it still has an issue with pulling.

I'll reach out to cloubees.  Thanks for the heads up by the way.

**Comment by s17t** [comment]
Thank you for quick support. We will continue to point to your cloudbees repo. I configured Travis to push to sonatype SNAPSHOT repository, just in case.
