### ISSUE TITLE
Huge amount of DEBUG logs after updating to 4.4.0.

### ISSUE THREAD

**Issue by LSmyrnaios** [yasserg/crawler4j#312]
Hi,
After updating to 4.4.0, I noticed a huge difference in the DEBUG logs.
The DEBUG logs from "org.apache.http" are flooding the console with full HTTP responses of any webPage that Crawler4j connects to.

Is there a way to avoid that? Through configuration or maybe through a hack?

I would really like to be able to see just the LOGS about visiting a page from Crawler4j and then my debug logs.

Thanks.

**Comment by s17t** [comment]
Would you share your logback.xml configuration ?

**Comment by LSmyrnaios** [comment]
Here it is. I want to see debug messages, but seeing full HTTP responses when running for thousands of URLs... is not so helpful.
I can log the URLs having unwanted behavior and go open them myself in a web browser.
But, as others may want to see this huge debug info.. I am looking for a parameterization approach.

```
<configuration debug="false">

    <appender name="File" class="ch.qos.logback.core.FileAppender">
        <file>logs/DocUrlsRetriever.log</file>
        <append>true</append>
        <encoder>
            <charset>UTF-8</charset>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <charset>UTF-8</charset>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M\(@%line\) - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="debug">
        <appender-ref ref="Console" />
    </root>

</configuration>
```

**Comment by s17t** [comment]
You can use logback features to set level for certain package. Something like:

```
   <logger name="org.apache.http" level="ERROR"/>

    <root level="debug">
        <appender-ref ref="Console" />
    </root>
```

**Comment by LSmyrnaios** [comment]
I added the following lines and everything is fine now with the logs.
Thank you for your support.

```
<logger name="org.apache.http" level="ERROR"/>
<logger name="edu.uci.ics.crawler4j.fetcher.SniPoolingHttpClientConnectionManager" level="ERROR"/>
```
