### ISSUE TITLE
Url domain detected wrongly

### ISSUE THREAD

**Issue by Mideen** [yasserg/crawler4j#317]
URL :: http://www.dummy.pb.gov.br/
Domain Detected via weburl.getDomain() :: pb.gov.br
Actual domain :: dummy.pb.gov.br

pb.gov.br is TLD(check here: [https://publicsuffix.org/list/effective_tld_names.dat](https://publicsuffix.org/list/effective_tld_names.dat) ) but crawler4j weburl object returned this as a domain.

**Comment by pgalbraith** [comment]
I believe this is really a duplicate of #318, the issue is caused by the same code not determining etld / private subdomain as per user expectation.
