### ISSUE TITLE
TLD List detection not working correctly 

### ISSUE THREAD

**Issue by Mideen** [yasserg/crawler4j#318]
While detection of URL domain, Crawler4j checks the TLD list.
consider the following 
URL :: http://dummy.edu.np
Domain detected via weburl.getDomain() :: edu.np, In TLD list they are specified ***.np** is a TLD but crawler4j detected edu.np as domain

**Comment by pgalbraith** [comment]
@yasserg @s17t @Mideen 

I took a stab at this issue because my unit tests were breaking on this particular class (because of the singleton, not because of this particular issue).  I don't really understand why there is a ```WebURL.getDomain()``` and ```WebURL.getSubDomain`` separated set of methods.  It's not immediately clear what the semantics are here, but from looking at the code and reading https://publicsuffix.org I'm inferring that the intention is for ```getDomain()``` to return the first domain above any public suffix (i.e. the "top level private domain") and ```getSubDomain``` to return any child portion of that.

My first gut reaction is that crawler4j has no business making this kind of determination (i.e. which part of the domain is publicly available to register).  I.e., I think that when a user calls ```getDomain()``` they should get the entire domain, and there shouldn't be any ```getSubDomain()``` method at all.

But, there was code written to do this, and a defect raised because it's not working the way someone else is expecting :-)  Can anyone explain the use case(s) here?  I think, at the very least, the method name ```getDomain()``` is confusing, and some clarity needs to be added to the API.
