### ISSUE TITLE
SEVERE: Fatal transport error: status code: 1005

### ISSUE THREAD

**Issue by jasonbronson** [yasserg/crawler4j#33]
Mar 01, 2015 9:50:14 PM edu.uci.ics.crawler4j.fetcher.PageFetcher fetchHeader
SEVERE: Fatal transport error: wordpress.com:443 failed to respond while fetching https://wordpress.com/ (link found in doc #0)
Non success status for link: https://wordpress.com/, status code: 1005, description: Fatal transport error - Is the server down ?
Mar 01, 2015 9:50:14 PM edu.uci.ics.crawler4j.crawler.WebCrawler onUnexpectedError
WARNING: Skipping URL: https://wordpress.com/, StatusCode: 1005, , Fatal transport error - Is the server down ?

**Comment by Chaiavi** [comment]
Wordpress.com doesn't like our crawler.

If you want to crawl it you need to change the userAgentString

**Comment by Chaiavi** [comment]
Please try and report back

**Comment by jasonbronson** [comment]
Yes it's working now thank you.
