### ISSUE TITLE
Question: collecting contextual information when crawling for binaries

### ISSUE THREAD

**Issue by cnsgithub** [yasserg/crawler4j#340]
Hi,

Sorry about posting a question in the issue tracker. I am not sure where to do that otherwise...

I am pretty new to crawler4j and I am trying to find and download some binary files available on a website.

Together with the downloaded binaries I'd like to store some contextual information like the title of the page the binaries were found, the surrounding link text, etc.

I know that `HtmlParseData` contains some information like title. However, within `WebCrawler.visit ` I do not have a back reference to the page including the binary, do I? As I understand it correctly, `WebCrawler` instances are created per thread and therefore could have a state like the last visited HTML page?

Could you please give me some clues what would be the best practice to achieve what I want?

Thanks

**Comment by shalipoto** [comment]
Are you using the `ImageCrawler` or `BasicCrawler`?

**Comment by cnsgithub** [comment]
@shalipoto How does that matter? I thought those are just two example implementations of `WebCrawler`?

**Comment by cnsgithub** [comment]
For those of you who want to achieve similar things, I've come up with this solution:

```java
public class MyCrawler extends WebCrawler {
   private static Map<WebUrl, MetaInfo> metaInfo = new ConcurrentHashMap<>();

   @Override
   public boolean shouldVisit(Page referringPage, WebURL url) {
      boolean shouldVisit = false;
      // ...
      if (shouldVisit) {
         MetaInfo m= new MetaInfo();
         // ...
         m.title = ((HtmlParseData) referringPage.getParseData()).getTitle();
         metaInfo.put(metaInfo);
      }
      return shouldVisit;
   }

   @Override
   public void visit(Page page) {
      // ...
      MetaInfo m = metaInfo.get(page.getWebURL());
      // ...
      metaInfo.remove(page.getWebURL());
   }

   static class MetaInfo {
      String title;
      // ...
   }
}
```

Please note that the map has to be declared as static since each worker thread will have its own `MyCrawler` instance and the actual `visit` is not necessarily called by the same thread as `shouldVisit`. Therefore it's necessary to use a `ConcurrentHashMap` or similar synchronized data structures.

It's also absolutely essential to remove cached items from the map after the meta information had been consumed to not introduce a memory leak.
