### ISSUE TITLE
redirected to NOTHING

### ISSUE THREAD

**Issue by klaushauschild1984** [yasserg/crawler4j#343]
Hi there,
the `WebCralers` redirect handling code is confuding me a little bit. There will be the redirect url be calculated. If the result is `null` just a warning is printed "redirected to NOTHING" and the method returns immediately.
I am using the crawler to verify no broken links nor redirects at my page. This behaviour bugs my because there is no way to handle it probably and I think it's a "problem" in my scenario because the redirect leads to nothing.
Thanks for your help and advice.

**Comment by s17t** [comment]
#376 added a specific event for "redirected to NOTHING". @klaushauschild1984 notice that happens only when "Location" header has invalid URL.
