### ISSUE TITLE
How to get url generate by javascript ?

### ISSUE THREAD

**Issue by fatekiller** [yasserg/crawler4j#344]
I am new in this project, and the page I want to craw generate it's pagination link via the javascript code, so the crawler4j can not add it to `outgoingUrls`, what method can I take to solve this problem
this is the code that generate the pagination link
```

function createPageHTML(_nPageCount, _nCurrIndex, _sPageName, _sPageExt){
--
   if(_nPageCount == null \|\| _nPageCount<=1){
   return;
   }
   var nCurrIndex = _nCurrIndex \|\| 0;
  if(nCurrIndex == 0)
   {
   document.write("<a><span class=\"f\">&laquo;</span>prev</a>&nbsp;");
   document.write("<span class='current'>1</span>&nbsp;");
   }
   else{
   var prePageNum = nCurrIndex-1;
   if (prePageNum == 0)
   document.write("<a href=\""+_sPageName + "."+_sPageExt+"\" ><span class=\"f\">&laquo;</span>next</a>&nbsp;");
   else
   document.write("<a href=\""+_sPageName+"_" + prePageNum + "."+_sPageExt+"\" ><span class=\"f\">&laquo;</span>上一页</a>&nbsp;");
   document.write("<a href=\""+_sPageName+"."+_sPageExt+"\" >1</a>&nbsp;");
  }


```

**Comment by shalipoto** [comment]
Crawler4j does not support javascript yet. It would be very good to support it as more modern crawlers are supporting javascript. One way to do it is for the crawler to make calls to Selenium, which is a browser, and let the browser run the javascript, update the HTML file and them pass the file to the crawler.

**Comment by fatekiller** [comment]
thanks for your reply, I will take a try :)
