### ISSUE TITLE
Tika parser fails to detect encoding

### ISSUE THREAD

**Issue by pgalbraith** [yasserg/crawler4j#346]
Starting a crawler with a single seed of http://c2.com fails after this error:

ERROR [Crawler 1] - [TikaHtmlParser]- Failed to detect the character encoding of a document, while parsing: http://c2.com/

**Comment by zbassil** [comment]
solved it by setting the content type metadata before calling parse in TikaHtmlParser

**Comment by pgalbraith** [comment]
Fixed in PR #368
