### ISSUE TITLE
Enable adding custom http headers when fetching urls

### ISSUE THREAD

**Issue by tgoetz** [yasserg/crawler4j#35]
As far as I can see there's currently no possibility of settings own http headers (either globally for all requests or on a per-request basis) when fetching urls. Or did I miss something?

**Comment by Chaiavi** [comment]
Can you please explain this feature request a bit ?

**Comment by tgoetz** [comment]
Ok, I will try ;-)

In a current crawling project, we need to supply a specific HTTP header (e.g. "Accept-Language") when fetching certain URLs in order to receive the content (response) we are interested in. The current crawler4j implementation uses HttpGet (from HttpClient) to fetch pages ([see here](https://github.com/yasserg/crawler4j/blob/3319b95643dd00dd84e6156654e73aaf148b0e0b/src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java#L203)), but there is no possibility to set http headers (globally for all requests or per-request).

The only solution I currently see is to subclass PageFetcher, override fetchPage(WebURL webUrl), copy the orignal code, and configure the HttGet accordingly.

**Comment by tgoetz** [comment]
An easy solution could be: 
move the creation of the HttpGet into a new factory method in `PageFetcher`, which is easyly overrideable, e.g.:

```java
protected HttpUriRequest newHttpRequest(String url) {
    return new HttpGet(url);
}
```

... and then, in `fetchPage(WebURL url)` (~line 198) you call:

```java
HttpUriRequest request = newHttpRequest(toFetchURL)
...
```

This would allow an easy (global) manipulation of e.g. the request headers IMHO.

**Comment by tgoetz** [comment]
I will provide a pull request, so you can have look at my proposal.

**Comment by Chaiavi** [comment]
Very good - thank you
