### ISSUE TITLE
Any way to append the manually-built URL to the crawler on-fly

### ISSUE THREAD

**Issue by vicmosin** [yasserg/crawler4j#366]
Since javascript isn't supported, it would be nice to be able to append some URLs (which can be generated in `shouldVisit` for example) to the crawler.. 
Imagine the following, we iterate pages, then found one with pagination list (which is 100% done in js) -> we generate the links based on current url + pagination parameters and add that list to crawler..

**Comment by pgalbraith** [comment]
I think you can already do this using ```myController.addSeed(url)```
