### ISSUE TITLE
BasicCrawler failed when crawling Baidu 

### ISSUE THREAD

**Issue by BobTheta** [yasserg/crawler4j#37]
Hi,

  I tried the simple crawler sample on the index page. It worked well when choosing Yahoo, Google and most of  other websites as seeds. However, it just failed with www.baidu.com. Is there any measure I can take to solve the problem?

ps：I can successfully get baidu pages using URLConnection.

Best regards.

**Comment by mashuai** [comment]
check the robots.txt  
```
User-agent: * 
Disallow: /
```

**Comment by Chaiavi** [comment]
You can work around this one by setting your crawler to ignore robots.



Next time, enable all logs and use the latest version of crawler4j - you
will see everything in the logs

**Comment by BobTheta** [comment]
Thank you ~
I've solved the problem by:
robotstxtConfig.setEnabled(false);
