### ISSUE TITLE
Url resolved as 400 because of wrongly encoded '+' character

### ISSUE THREAD

**Issue by ukul3l3** [yasserg/crawler4j#374]
Url https://fonts.googleapis.com/css?family=Roboto+Condensed&subset=cyrillic encoded to https://fonts.googleapis.com/css?family=Roboto%2BCondensed&subset=cyrillic not to https://fonts.googleapis.com/css?family=Roboto%20Condensed&subset=cyrillic.

This stackoverflow question is also about this problem https://stackoverflow.com/questions/48678356/crawler4j-seed-url-gets-encoded-and-error-page-is-crawler-instead-of-actual-page

**Comment by s17t** [comment]
The current code is correct against the RFC3986 ( '+' is encoded to '%2B', see also the tests in URLConicalizerTest). The fact is that the matter is a bit more complicated, see for a good answer [0]. 

Many, too many legacy (and not-so-legacy) systems have semantics on literal plus sign in query string.
The specific case of github API is a topical: the search API works if you omit the plus sign and use literal space. The space is encoded to %20 and the search works.

`https://github.com/search?q=java location:India&p=1`

That said, we should support to specify the URL encoder on a per-URL base.

[0] https://stackoverflow.com/a/47188851/4510569
