### ISSUE TITLE
Is crawler4j configurable to setup period of time to do crawling constantly

### ISSUE THREAD

**Issue by johnklee** [yasserg/crawler4j#380]
As title. We may need to monitor specific site for update. So we want the configuration to setup the crawler4j to periodically crawl specific site/url.

**Comment by pgalbraith** [comment]
I don't believe so, you'd need to wrap the crawler in some sort of external scheduling mechanism (e.g. maybe a cron job, or something more sophisticated like Control-M if your organization has a formal batch job infrastructure.

You might also (I've never tried this myself) be able to use a java scheduling library like [Quartz](http://www.quartz-scheduler.org/), but I've never done this myself.

**Comment by s17t** [comment]
At the moment C4J does not have infrastructure for scheduling but you can easily patch together one using the already cited [Quartz](http://www.quartz-scheduler.org/) or some command scheduler like plain old cron or Jenkins.
