### ISSUE TITLE
Allow others to merge to repo, move to an organization proposal

### ISSUE THREAD

**Issue by s17t** [yasserg/crawler4j#384]
@yasserg Since days my user is not able merge into repo anymore. Would you  allow my user again to merge ? In alternative, I created the "crawler4j" organization, would you agree to move the main repo in that organization ? I would give admin access to that organizatio, of course.

**Comment by s17t** [comment]
I have created an organization https://github.com/crawler4j/crawler4j with an import of the main repo. I have added @yasserg as admin (we will see if he will respond). @pgalbraith , @rzo1 and @Chaiavi have write permission in the repo.

**Comment by pgalbraith** [comment]
@yasserg do you have any thoughts?  We certainly don't want to do anything against your wishes, any feedback here would be valuable.  Thanks!

**Comment by pgalbraith** [comment]
Thanks @yasserg, I certainly understand and respect that.
