### ISSUE TITLE
I want to path args to shouldVIsit() method in crawler4j.

### ISSUE THREAD

**Issue by engsakr** [yasserg/crawler4j#392]
Please, I want a sample example about how to pass args to shouldVisit() method in crawler4j ..
I cant understand the factory way so, I hope you to provide a sample example .
Thanks in advance

**Comment by yasserg** [comment]
what args? what are you trying to do?

**Comment by engsakr** [comment]
I want to path object which gives me specific data from database , as a constructor dependency injection

**Comment by engsakr** [comment]
It is what I want , I want to path Project object in shouldVisit method but does not work ..


public boolean shouldVisit(Page referringPage, WebURL url , Project project) {
        String href = url.getURL().toLowerCase();
        // Ignore the url if it has an extension that matches our defined set of image extensions.
        if (IMAGE_EXTENSIONS.matcher(href).matches()) {
            return false;
        }

        // Only accept the url if it is in the "www.ics.uci.edu" domain and protocol is "http".
        return href.startsWith("https://www.ics.uci.edu/");
    }

**Comment by yasserg** [comment]
I have updated the basic example to show how to pass objects to crawlers. You need to use a factory: https://github.com/yasserg/crawler4j/blob/master/crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/basic/BasicCrawlController.java  (it shouldn't be passed to shouldVisit, instead it should be passed to constructor)

**Comment by yasserg** [comment]
See this: https://github.com/yasserg/crawler4j/commit/38561817a43becc13f1e42a42d8177005ed0f3e4
