### ISSUE TITLE
Not able to crawling with Login credential 

### ISSUE THREAD

**Issue by sw-tt-hardikgajjar** [yasserg/crawler4j#396]
Hello , 

i try to crawling the website with their credential , with FormAuthInfo & BasicAuthInfo but its seems not crawling the inner pages which access after Login.

i also try with github website

  AuthInfo authInfo1 = new FormAuthInfo("hardik.gajjar@XXXX.com", "XXXXX","https://github.com/login","login", "password");
 config.addAuthInfo(authInfo1);
 
AuthInfo authInfo2 = new BasicAuthInfo("hardik.gajjar@XXXX.com", "XXXXX","https://github.com/login");
 config.addAuthInfo(authInfo2);

in github url its not going any page or url for crawling.

can you please suggest?

Thanks.
Hardik

**Comment by forrestlmj** [comment]
hello,maybe use cookie instead of login?

**Comment by yasserg** [comment]
Most of the websites including github don't allow basic or form-based authentication
