### ISSUE TITLE
Crawler downloads entire content before checking maximum download size

### ISSUE THREAD

**Issue by nodesman** [yasserg/crawler4j#4]
The crawler should ideally check the size of data as it is received instead of downloading all the data and then checking whether it is too much. This feature is of interest so that users can prevent downlaoding massive data which could end up crashing the process.

**Comment by davidacampos** [comment]
Several years later, but it's still an issue... the way we overcome this was by subclassing the PageFetcher and overriding the fetchPage method... we added some logic to perform a HEAD instead of a GET on known filetypes (which has another limitation... the fact that only work for known filetypes; but works fine for our use case).

```java
private final static Pattern DOWNLOAD_EXCLUSIONS = Pattern.compile(".*(\\.(js|css|mp4|pdf|iso|zip|tar|7z|gz|rpm)).*$");
```

```java
 @Override
    public PageFetchResult fetchPage(WebURL webUrl) throws InterruptedException, IOException, PageBiggerThanMaxSizeException {
        String toFetchURL = webUrl.getURL();

        if (DOWNLOAD_EXCLUSIONS.matcher(toFetchURL).matches()) {
            PageFetchResult fetchResult = new PageFetchResult();
            HttpHead head = null;
            try {
                head = new HttpHead(toFetchURL);

                synchronized (this.mutex) {
                    long now = new Date().getTime();
                    if (now - this.lastFetchTime < this.config.getPolitenessDelay()) {
                        Thread.sleep(this.config.getPolitenessDelay() - (now - this.lastFetchTime));
                    }
                    this.lastFetchTime = new Date().getTime();
                }

                HttpResponse response = this.httpClient.execute(head);
                fetchResult.setEntity(response.getEntity());
                fetchResult.setResponseHeaders(response.getAllHeaders());
                fetchResult.setFetchedUrl(toFetchURL);
                fetchResult.setStatusCode(response.getStatusLine().getStatusCode());

                return fetchResult;
            } finally {
                if (head != null)
                    head.abort();
            }
        } else {
            return super.fetchPage(webUrl);
        }
    }
```

**Comment by Chaiavi** [comment]
I don't understand your solution.

Your fix downloads only the headers for binary file types.


If you don't want the binary files, you can configure the crawler not to download binary files, or you can use your shouldVisit() method to add there a limitation for certain file types.


If file download size is the concern (even of html pages) the crawler has a setMaximumPageSize configuration you can set, which in many cases works fine (not on all cases, as some files don't have the size in their headers etc).

Restricting the file size download is a problem which is hard to overcome as it is hard to predict file sizes before download and a lot of time goes for the actual networking overhead even before downloading the first byte.

Checking the header of binary files is very wasteful for small images (like most graphics of html pages) but can be good for big binary files like large (several mb) of zip files, mp3 etc.

Just don't forget that the actual fetching of headers takes some time as the overhead of networking is used, and I suggest limiting by using the shouldVisit() (like in BasicExample) or by disabling download of binary files altogether (or both for best results)



Avi.

**Comment by davidacampos** [comment]
OK, makes sense, so might be easier if I tell you the reason why we are using the library. We are not using it to crawl the content, but more like to check the content... we want to check that there are no broken links (404).

After clarifying that, the reason for not using the "shouldVisit" is because I don't want to exclude those files, but I don't need the content either, I essentially just need to see if they exist or not.

**Comment by s17t** [comment]
There is a solution on how do something similar to this in 98aaa96. There are cases where either using or not using HEAD to check size or type of the resource is wasteful. I think it is better don't touch the original implementation but  allow user to implement preferred strategy. Close.
