### ISSUE TITLE
Getting processed pages out of crawler4j

### ISSUE THREAD

**Issue by w0mbat** [yasserg/crawler4j#43]
Hey folks,

I currently need to get the total number of processed pages out of crawler4j.
So far, we are working with localData Objects, which work fine, as long as we do not have to resume the crawling. If we do or have to do it, only the pages from the current crawling are counted and all previous pages are missing.

Is there a better and easier way of getting this information?

Best regards,

Daniel

**Comment by yasserg** [comment]
No, we didn't implement anything specific for that.

**Comment by w0mbat** [comment]
Do you have a hint for me, where we would need to start, to make this possible?
