### ISSUE TITLE
configurable slf4j logger

### ISSUE THREAD

**Issue by leder11011** [yasserg/crawler4j#438]
Hi,

how can I configure the output not to show DEBUG messages? Please make the logger adaptable!

Thanks!

Cheers
Gerrit

**Comment by Chaiavi** [comment]
Go here <https://github.com/yasserg/crawler4j/find/master>

Search for "log"

The 3 first files are logback configuration files used for our examples
projects etc.

**Comment by leder11011** [comment]
That was a great hint: top project! Thank you all!

**Comment by naoxide95** [comment]
Hi!
I'm trying to do as instructed, but I'm not able to do so.. I downloaded the sources, included is in my project, and I was able to implement the needed classes and run the code, and it's raining loggings.
How is "logback.xml" related when it's located outside the package?
