### ISSUE TITLE
Crawling https://developress.netsons.org returns 0 pages

### ISSUE THREAD

**Issue by loxal** [yasserg/crawler4j#439]

**Comment by Chaiavi** [comment]
Please post the stacktrace

**Comment by loxal** [comment]
There is no stacktrace, everything goes smoothly. `shouldVisit` returns true for at least 17 pages but `visit` is never entered.

**Comment by dgoiko** [comment]
You should run in debug mode and follow the execution of WebCrawler processPage method.

**Comment by loxal** [comment]
`config.isRespectNoIndex = false`

...solved the problem. Many sites revert to using per-page robot directives. So this is a non-bug issue.
