### ISSUE TITLE
Not working with JDK 17

### ISSUE THREAD

**Issue by mehikmat** [yasserg/crawler4j#467]
It's giving issue with JDK 17

```
Feb 05, 2022 11:31:00 AM com.sleepycat.je.utilint.DaemonThread run
SEVERE: <DaemonThread name="StatCapture"/> caught exception, java.lang.IllegalStateException: java.lang.IllegalAccessException: class com.sleepycat.je.utilint.JVMSystemUtils cannot access class sun.management.BaseOperatingSystemImpl (in module java.management) because module java.management does not export sun.management to unnamed module @647c3190 Continuing
java.lang.IllegalStateException: java.lang.IllegalAccessException: class com.sleepycat.je.utilint.JVMSystemUtils cannot access class sun.management.BaseOperatingSystemImpl (in module java.management) because module java.management does not export sun.management to unnamed module @647c3190
	at com.sleepycat.je.utilint.JVMSystemUtils.getSystemLoad(JVMSystemUtils.java:50)
	at com.sleepycat.je.statcap.JvmStats.loadStats(JvmStats.java:81)
	at com.sleepycat.je.statcap.StatCapture.getStats(StatCapture.java:223)
	at com.sleepycat.je.statcap.StatCapture.outputStats(StatCapture.java:169)
	at com.sleepycat.je.statcap.StatCapture.onWakeup(StatCapture.java:142)
	at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:148)
```

**Comment by liukuan1** [comment]
您的邮件我已收到，我将及时查看！谢谢！

**Comment by mehikmat** [comment]
Thanks, Meanwhile I added `--add-exports java.management/sun.management=ALL-UNNAMED` and it fixed the issue. Not sure if it's the correct way to fix.

**Comment by appreciated** [comment]
@mehikmat thanks for the hint, but it seems there is a typo in your workaround
`--add-exports java.management/su**m**.management=ALL-UNNAMED` .
`--add-exports java.management/sun.management=ALL-UNNAMED` worked for me.

**Comment by liukuan1** [comment]
您的邮件我已收到，我将及时查看！谢谢！

**Comment by epubreader** [comment]
什么时候发布新版本？

**Comment by epubreader** [comment]
> @mehikmat thanks for the hint, but it seems there is a typo in your workaround `--add-exports java.management/su**m**.management=ALL-UNNAMED` . `--add-exports java.management/sun.management=ALL-UNNAMED` worked for me.

怎么修改代码升级sleepycat?

**Comment by nAoxide** [comment]
> Thanks, Meanwhile I added `--add-exports java.management/sun.management=ALL-UNNAMED` and it fixed the issue. Not sure if it's the correct way to fix.

could you please, send a hint, where to put that line?

**Comment by appreciated** [comment]
> could you please, send a hint, where to put that line?

Add it to the command line when running your Java application:
```
java --add-exports java.management/sun.management=ALL-UNNAMED -jar your-application.jar
```

**Comment by nAoxide** [comment]
> > could you please, send a hint, where to put that line?
> 
> Add it to the command line when running your Java application:
> 
> ```
> java --add-exports java.management/sun.management=ALL-UNNAMED -jar your-application.jar
> ```

Appreciate the help, sir.
Thank you very much!
