### ISSUE TITLE
Search in Google

### ISSUE THREAD

**Issue by feliperce** [yasserg/crawler4j#71]
How to make the crawler search and follow Google Results?

**Comment by Chaiavi** [comment]
Crawl the google page while having the search term in the url as follows:
https://www.google.co.il/search?q=SEARCH_TERM


But please bear in mind that if you will try too many of those google will
mark you as a spammer


Which you can pass by using proxies which makes it much more complicated
and I am not sure that it is worthwhile

**Comment by feliperce** [comment]
But if I use the google link witch the search term, the crawler don't jump in pages and get the results, he jump i all google links (youtube, gmail, play store, contact, images, maps, about, privacy terms, and all others links in google)

**Comment by Chaiavi** [comment]
Right


You will then need to parse the page and find only the link you want...

I would use JSoup to parse the page using the CSS selectors

**Comment by feliperce** [comment]
I will take a look

**Comment by feliperce** [comment]
closed unintentionally, lol

**Comment by Chaiavi** [comment]
This issue can be closed now
