### ISSUE TITLE
Can't crawl Wikipedia HTTPS pages

### ISSUE THREAD

**Issue by MarioGomezR4** [yasserg/crawler4j#76]
Hi. I'm Mario and I hope you can help me guys!

I'm using Google's Crawler4j to download text from:

https://es.wikipedia.org/wiki/David_Gilmour

Two weeks ago this library worked fine, but now it complains with:

"ERROR edu.uci.ics.crawler4j.fetcher.PageFetcher  - Fatal transport error: null while fetching https://es.wikipedia.org/wiki/David_Gilmour/ (link found in doc #0)"

Could the problem be related to:

1. httpS?

2. Wikipedia disabled crawling on their site?

In case of 2, is there any workaround I can apply?

Thank you very much for your time!

**Comment by Chaiavi** [comment]
Can you upgrade to the latest version of crawler4j?

Then retry and report ?
בתאריך 1 ביולי 2015 21:17,‏ "MarioGomezR4" <notifications@github.com> כתב:

**Comment by MarioGomezR4** [comment]
Thanks for your quick response! I'm already using the latest 3.5 version. Is there a newer one I didn't see??

**Comment by MarioGomezR4** [comment]
I downloaded the 3.5 version from:

https://code.google.com/p/crawler4j/downloads/list

**Comment by MarioGomezR4** [comment]
Sorry! I just discovered this:

https://github.com/yasserg/crawler4j/releases

**Comment by MarioGomezR4** [comment]
I'll give it a try and let you know. Sorry for the inconvenience...

**Comment by MarioGomezR4** [comment]
The 4.1 version works like a charm! Thanks and sorry again for my "bad eye".

**Comment by Chaiavi** [comment]
No sweat.



Keep Crawling
