### ISSUE TITLE
Implement crawler trap detection

### ISSUE THREAD

**Issue by nicosensei** [yasserg/crawler4j#8]
Crawler traps are URL patterns that the crawler should not attempt to visit, as they are either:
- not desired within a specific crawl
- will cause the crawler to get stuck in loops (for instance forum registration)

A crawler trap is specified by a Java regular expression, such as (?i)^._forum[s]?._post_reply.cfm=.*$

Traps will be loaded from flat text files, one trap expression by line.

**Comment by Chaiavi** [comment]
Can you please point me to a site which has a crawler trap ?

Can you please point me to the fix in the code ?

**Comment by Akibalogh** [comment]
this could also be mitigated by setting depth, i.e. depth = 10

**Comment by rzo1** [comment]
Or by limiting / parametrize the maximum length of an url (see related literature...)

**Comment by s17t** [comment]
Absolutely can be avoided implementing right logic in `shouldVisit` method.
