### ISSUE TITLE
Factory instead of hardcoded class.newInstance() 

### ISSUE THREAD

**Issue by rzo1** [yasserg/crawler4j#84]
I would like to suggest, that adding a the possibility to use a factory to create new web-crawlers would be of great value.

Since a web-crawler could hold a few custom services (e.g. classifiers, database services) a factory would be a very nice thing to make crawler4j usable for example via Spring.

A few years ago an issue was created on googlecode (https://code.google.com/p/crawler4j/issues/detail?id=144), which is a duplicate of mine request - but nothing happend. Is there a reason for not including a factory approach in the code-base?

Thanks in advance.

**Comment by yasserg** [comment]
It is already implemented but not well documented yet. See WebCrawlerFactory in https://github.com/yasserg/crawler4j/blob/master/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java

**Comment by rzo1** [comment]
A i see - thanks for your answer - but it is not included in the current release of crawler4j? 
So i probably have to use the SNAPSHOT, if i like to use this feature?

**Comment by yasserg** [comment]
Yes

**Comment by s17t** [comment]
+1 for factory or any way that allow dependency injection. Any scheduled for new stable that includes this feature ?

**Comment by rzo1** [comment]
@s17t Just get the source code and build the current SNAPSHOT by yourself. The snap implements a WebCrawlerFactory, which you can use for DI e.g. with Spring.

**Comment by eimhee** [comment]
I know you have added WebCrawlerFactory, but How to use spring DI? can you give an example? thanks

**Comment by s17t** [comment]
@eimhee, something like this:
```
public class CrawlerCrawlerControllerFactory implements CrawlController.WebCrawlerFactory {

   public CrawlerCrawlerControllerFactory(...) {
    ...
   }

    @Override
    public WebCrawler newInstance() {
        return new edu.uci.ics.crawler4j.crawler.WebCrawler(...) // Or new instance of your WebCrawler children class
}
```

Then in spring:

```
@Bean
public CrawlController crawler() {

     CrawlerCrawlerControllerFactory factory = new CrawlerCrawlerControllerFactory(...);

    // Configure CrawController accordingly...
    CrawlController controller = new CrawlController(config, pageFetcher, robotstxtServer);
    controller.startNonBlocking(factory, numberOfCrawlers);
   
   return controller 
}
```

**Comment by rzo1** [comment]
As an alternative, you could implement `ApplicationContextAware` and get a WebCrawler-Bean from your ApplicationContext.

```
public class CustomCrawlerFactory<T extends WebCrawler> implements CrawlController.WebCrawlerFactory<T>, ApplicationContextAware {

    private ApplicationContext context;

    @Override
    public T newInstance() throws Exception {
        return (T) context.getBean(MyCrawler.class);
    }
	
	@Override
    public void setApplicationContext(ApplicationContext context) {
        this.context = context;
    }
}
```
