### ISSUE TITLE
JVM heap size keeps increasing considerably

### ISSUE THREAD

**Issue by b-abderrahmane** [yasserg/crawler4j#88]
What steps will reproduce the problem?
1.a while loop ( creating crawlController and crawling a website ) at each iteration
2. the crawlController have been slightly modified so it could have something to do with it

What is the expected output? What do you see instead?

After each crawling operation, the heap size is supposed to go back the way it was before it, seeing how it's a series of independent operations.

but instead, the heap size keeps increasing with no end until it crashes.

What version of the product are you using?

3.5

Please provide any additional information below.

After using yourKit Java profiler to locate what lines of code were exactly consuming this memory, I ended up at this : 

Environment env = new Environment(envHome, envConfig);

this line from the crawlController, was consuming over 620 MB from a total of 650 MB.

Now I don't know what's exactly in this env object so I can't diagose it, but I hope you guys can help me with that.

I will include a screenshot from the profiler's result 

![crawler_odesk123456](https://cloud.githubusercontent.com/assets/10504574/8946026/aaab0086-3584-11e5-9cda-6048b496156f.jpg)

**Comment by Chaiavi** [comment]
Please upgrade to the latest version, we solved several memory leaks there.


I hope it solves this one too

**Comment by s17t** [comment]
Please update to latest version: 4.4.0
